### ISSUE TITLE
Think about tables

### ISSUE THREAD

**Issue by gaborcsardi** [rstudio/shinytest#10]

**Comment by gaborcsardi** [comment]
Something like this, maybe:

* `get_table_info` for metadata: i.e. num of rows, cols, whether the search bar is there, etc. basically the options of the JS widget
* `get_table` get the table as a data frame
* `get_table_cell` to get the value of a single cell
* `get_table_column` to get the column as a vector (list?)

**Comment by gaborcsardi** [comment]
I need to see what is different between `DT` and plain shiny tables, if anything....

**Comment by hadley** [comment]
Closing and tracking collectively.
