### ISSUE TITLE
Travis CI "Error in session_makeRequest, can't find variable: $"

### ISSUE THREAD

**Issue by jstockwin** [rstudio/shinytest#100]
I get the following error on my travis CI build [here](https://travis-ci.com/jstockwin/TransmissibilityEstimator/jobs/71473667#L195). 

```
$ Rscript -e "library(shiny); library(shinytest); testApp()"
Loading required package: methods
  Can't find variable: $
Calls: testApp ... session_executeScript -> <Anonymous> -> session_makeRequest -> report_error
Execution halted

The command "Rscript -e "library(shiny); library(shinytest); testApp()"" exited with 1.
```

Am I missing something? My `.travis.yml` is [here](https://github.com/jstockwin/TransmissibilityEstimator/blob/testing/.travis.yml).

**Comment by jstockwin** [comment]
Ah, oops, I've just realised my project isn't public yet so those links won't work. 

Here's the important part of `.travis.yml`:

```
before_script:
  - Rscript -e "install.packages('devtools')"
  - Rscript -e "devtools::install_github('rstudio/shiny')"
  - Rscript -e "devtools::install_github('rstudio/shinytest')"
script:
  - Rscript -e "library(shiny); library(shinytest); testApp()"
```

**Comment by wch** [comment]
This may be happening because the Shiny app is not starting correctly. For example, if your app uses a package that is not installed on the test system, it will give an error like this.

We are working on improving the error logging to make these situations easier to diagnose.

**Comment by wch** [comment]
f0eab6a and c29b789 improve the logging so that this should be easier to diagnose. Additionally, you may need to install a newer version of PhantomJS -- the version that's installed by default on Travis is outdated and doesn't support all features that shinytest uses. You can look at the .travis.yml file for this repo to see how we're installing version 2.1.1.
