### ISSUE TITLE
Testing inputs - edge case

### ISSUE THREAD

**Issue by bborgesr** [rstudio/shinytest#105]
Here is the problem. Imagine that we have the following app below:

```r
ui <- fluidPage(
  actionButton("add", "Add table", icon = icon("th")),
  tags$div(id = "tables")
)

server <- function(input, output, session) {
  observeEvent(input$add, {
    id <- paste0("slider-", input$add)
    insertUI("#tables", "beforeEnd", DT::dataTableOutput(id))
    output[[id]] <- DT::renderDataTable(head(mtcars, 3), server = FALSE)
  }, ignoreInit = TRUE)
}

shinyApp(ui, server)
```

I wanted to interact with (and test) this app in a specific way: I wanted to create one table, highlight a few rows, then create a second table and make sure that the highlighted rows from the first table are still there. This is not possible right now.

The first problem I encountered was that if you select rows when you run `recordTest()`, shinytest gets confused and even though it records the test and produces a tests directory, these are only for first snapshots (before clicking any rows and losing the rest of the information). This is especially bad because while you test the app (including selecting rows), there’s no indication anything is going wrong.

However, as soon as you finish recording the test, you get an error:
```r
> recordTest(“apps/insertUI-test”)

Listening on http://127.0.0.1:7005
Saved test code to /Users/barbaraborges/shinyTestResults/apps/insertUI-test/tests/mytests.R
Saving baseline...
Error in session_makeRequest(self, private, endpoint, data, params, headers) :
  Unable to find input binding for element with id DataTables_Table_0_length
```

You get the same error when you try to test it:

```r
> testApp(“apps/insertUI-test”)
====== Running mytests.R ======
  Error in session_makeRequest(self, private, endpoint, data, params, headers) :
  Unable to find input binding for element with id DataTables_Table_0_length
```

You can get around this by manually editing the test script and commenting out any line that sets one of the "meta" DT inputs. In this case, it was the setting of each datatable's length (`app$setInputs(DataTables_Table_0_length = "10")`) that was creating problems.

However, I still can't test what I originally set out to test, which was whether or not the rows of the first datatable remain highlighted when I add a second one...

**Comment by hadley** [comment]
Now part of #49
