### ISSUE TITLE
Feature request: allow certain differences in JSON to be ignored in the tests

### ISSUE THREAD

**Issue by bborgesr** [rstudio/shinytest#107]
@wch Capturing our exchange on Slack about this.

With an app with a DT (and probably other widgets or htmlwidgets), the `sessionId` and `nonce` from Shiny are some recorded as part of the DT's metadata ([example](https://github.com/rstudio/shinyTestResults/blob/master/apps/dt-test/tests/mytests-expected/001.json)). These obviously will always vary, so `testApp()` tells you there are diffs in all of the JSON snapshots (but none in the PNG ones). Since the PNG snapshots don’t change and the JSON diffs make it clear that only these parts changed, maybe that’s ok. But I was wondering: it may be nice to let users set a diff ignore of some kind (or we do it for specific keywords like session and nonce, and let users opt into it). 

@wch mentioned that "we’ll need some way to filter out those values -- something configurable, and not hard coded, so that people who write their own additions to Shiny can use the same mechanism"

**Comment by sjspielman** [comment]
+1 for this feature request. For example, shiny applications w/ interactive networks where the coordinates are likely to change, but coordinate diff's should not invalidate the test.

**Comment by hadley** [comment]
You can now use `snapshotPreprocess()` or test individual elements using the approach of https://mastering-shiny.org/scaling-testing.html#testing-interaction.
