### ISSUE TITLE
"Recorded events" misbehaves with many events -- Safari 9.1.2 (running on El Capitan)

### ISSUE THREAD

**Issue by bborgesr** [rstudio/shinytest#108]
The recorded events widget usually works well. Even if we have tons of events, on browsers like Chrome and Firefox, the table looks prrety good and it scrolls nicely as the list of event grows. For exmaple, this is what it looks like on Chrome:

![screen shot 2017-06-19 at 9 35 54 pm](https://user-images.githubusercontent.com/6527540/27305057-1c1c88f0-5538-11e7-8368-e5be1861f6af.png)

However, it doesn't do so well for tons of events if you're on a Mac running El Capitan and using Safari (9.1.2) or the RStudio viewer.

Safari:
![screen shot 2017-06-19 at 9 34 22 pm](https://user-images.githubusercontent.com/6527540/27305116-49f54956-5538-11e7-8be3-f29913615e5b.png)

RStudio Viewer:
![screen shot 2017-06-19 at 9 34 11 pm](https://user-images.githubusercontent.com/6527540/27305136-585bab2a-5538-11e7-9041-4479dd3fbdc6.png)

**Comment by wch** [comment]
Fixed in ad688c3.
