### ISSUE TITLE
Feature request: snapshot on app startup and exit

### ISSUE THREAD

**Issue by bborgesr** [rstudio/shinytest#109]
Feel free to close this, I haven't really thought through its implications. BUT, it's crossed my mind a few times that it would be super useful if shinytest (either by default or opt-in) would automatically snapshot the app the first time it's idle (`one("shiny:idle")`) and when the user clicks "Quit and save" (so essentially capturing the very last state of the app).

I think this would be useful because, sometimes, when I'm testing, I just want to check something (select a row in a DT, for example), and it's kind of annoying to go through the ritual of snapshotting the starting state, doing the action and then snapshotting again the final state. This is especially frustrating when you have a few things that you do and once you exit, you find the message:

> No snapshot or download events occurred; not saving test code.

And you're left with no test script. So, I think that automatically snapshotting the final state (at least) might be a good idea. Is there any reason otherwise?

**Comment by wch** [comment]
As of edd06ef, it now shows a modal if the user clicks on Save and Exit and there are no snapshots. I don't think it's a good idea to automatically have a snapshot on startup -- there are many cases where you wouldn't want to do that, and it's easy enough to edit a script and add it in.
