### ISSUE TITLE
Provide reproducible example in documentation

### ISSUE THREAD

**Issue by daattali** [rstudio/shinytest#11]
+1 for adding man pages

In the Examples section of `?shinyapp`, instead of saying `shinyapp$new("050-kmeans-example")` it'd be nice to give a path to the code of that app

**Comment by daattali** [comment]
Nevermind, I understand now that the Usage section is not meant to be a full example, just the names of functions that can be run.  Because I saw so much code in there I assumed it was an actual example.

**Comment by gaborcsardi** [comment]
:+1: Yeah, it would be nice to break up the large manual page(s).

**Comment by gaborcsardi** [comment]
:+1: Indeed.

**Comment by daattali** [comment]
@wch I still think there should be a reproducible walkthrough example as soon as possible in the documentation. Maybe in https://rstudio.github.io/shinytest/articles/shinytest.html where it says to run `recordTest("path/to/app")` there can be an example below it for using recordTest on one of the example shiny apps that are provided by the shiny package?
