### ISSUE TITLE
More Safari bugs ("Difference" view for images not working and text overlay)

### ISSUE THREAD

**Issue by bborgesr** [rstudio/shinytest#110]
The built in diff tools works wonders in Chrome and Safari. However, it doesn't do so when you want to see the "Difference" view of an image -- if you're on a Mac running El Capitan and using Safari (9.1.2) or the RStudio viewer. Interestingly, all other image views ("Toggle" and "Slider") work fine.

Here's the problem -- simply nothing shows up for Safari/RStudio Viewer for the "Difference" view:
![screen shot 2017-06-19 at 10 16 51 pm](https://user-images.githubusercontent.com/6527540/27306859-398a2120-553f-11e7-88df-03bd0d0bc808.png)

But as soon as you change to another view, it displays just fine:
![screen shot 2017-06-19 at 10 16 56 pm](https://user-images.githubusercontent.com/6527540/27306879-49919bd4-553f-11e7-9474-fc7180ddc009.png)

----

Also, notice the overlaying of the text at the top. Again, this is a Safari-/Rstudio Viewer-only bug. And it has to do with the size of the window (the smaller the window, the more noticeable the problem). The best way I can describe it is that even though the header still behaves like a sticky header, it's a "leaky" sticky header. This seems more directly related to #108 than the other issue described above.

**Comment by wch** [comment]
For the record, this appears to work on more recent version of Safari, 10.1.1 (12603.2.4).

**Comment by wch** [comment]
Fixed in ad688c3.
