### ISSUE TITLE
gray screen on recordTest()

### ISSUE THREAD

**Issue by ndimhypervol** [rstudio/shinytest#114]
I have a shiny app embedded in an R package, and I am pointing to the directory with the shiny app when running recordTest(), yet I get an immediate gray screen with no error in the console. When I do runApp() with the same directory, there is no problem and the app runs fine. What could be going wrong? If more details are needed, I'd be happy to try and provide them. Thank you.

**Comment by wch** [comment]
Can you supply a reproducible example, as well as the output of `devtools::session_info()`?

**Comment by ndimhypervol** [comment]
I made a simplified example, and I think I narrowed the problem down to renderLeaflet(). When I comment out all leaflet references and just render the table, recordTest() works fine. Uncomment them and it breaks. Is this a known problem? Thanks.

ui.R
`shinyUI(tagList(
  navbarPage(title='App',
             tabPanel("A", value=1),
             
             fluidRow(column(4, wellPanel(
               textInput("spName", label = "Enter species scientific name", placeholder = 'format: Genus species', value = 'Puma concolor'),
               sliderInput("occNum", "Maximum number of occurrences:", min = 1, max = 500, value = 50),
               actionButton("goDbOccs", "Query Database")
             )
             ),
             column(8, tabsetPanel(
               # tabPanel('Map', leaflet::leafletOutput("map", height=600)),
               tabPanel('Tbl', DT::dataTableOutput('occTbl'))
                                   
             )
             )
             )
  )
))
`
server.R
`shinyServer(function(input, output, session) {

  # # create map
  # m <- leaflet() %>% setView(0, 0, zoom = 2) %>% addProviderTiles('Esri.WorldTopoMap')
  # output$map <- renderLeaflet(m)
  # 
  # # create map proxy to make further changes to existing map
  # map <- leafletProxy("map")
  
  formatSpName <- function(spName) paste(strsplit(spName, split=' ')[[1]], collapse='_')
  
  dbOccs <- reactive({
    req(input$spName)
    
    # query database
    withProgress(message = paste("Querying", input$occDb, "..."), {
      q <- spocc::occ(input$spName, 'gbif', limit=input$occNum)
    })
    
    # extract occurrence tibble
    recs <- q[['gbif']]$data[[formatSpName(input$spName)]]
    return(recs)
  })
  
  observeEvent(input$goDbOccs, {
    # map %>% addCircleMarkers(data = dbOccs(), lat = ~latitude, lng = ~longitude)
    output$occTbl <- DT::renderDataTable(dbOccs())
  })
})`

**Comment by ndimhypervol** [comment]
Just checking in. Was this example sufficient to point out the issue? Thanks.

**Comment by wch** [comment]
Sorry, I've been busy with some other things and haven't had time to investigate. Hopefully I'll be able to look at it early next week.

**Comment by ndimhypervol** [comment]
Checking in again. Any updates for this fix? Thanks.

**Comment by wch** [comment]
Apologies for the long delay. I was able to record a test, but I needed to modify the app with `library(leaflet)` on top. It's possible that some other change in shinytest also made a difference.

It would be better if `recordTest()` captured and displayed errors from the Shiny process. I'll file another issue about that.
