### ISSUE TITLE
Unable to run `recordTest()` with version 1.1.2

### ISSUE THREAD

**Issue by daattali** [rstudio/shinytest#116]
Just installed shinytest and shiny v1.0.3.9002

The last time I tried shinytest in February I was able to run it fine (Win7).

I'm now on the same machine (newer R version) and unable to run it. Every time I try, the first time I get an error:

```
> recordTest("appfolder")
Error in write_lines_named_pipe.windows_named_pipe(supervisor_info$stdin,  : 
  An error occurred when writing to the named pipe. Error 536. No process is listening on other end of pipe.
```

And the second time I try to run it, RStudio crashes.

I've repeated this process 4 times with different folders, every time I get this short loop of error then crash

**Comment by wch** [comment]
This is likely due to an issue in processx that we have a possible fix for. Can you try installing this in a clean R session?

```R
devtools::install_github('wch/processx@supervisor-ready')
```

**Comment by daattali** [comment]
Yes that solves it
