### ISSUE TITLE
Suggestion: `recordTest()` should force the shiny app to open in browser

### ISSUE THREAD

**Issue by daattali** [rstudio/shinytest#117]
My RStudio is set to open shiny apps in the Viewer pane by default (quicker for development). Running `recordTest()` starts up the recording app inside RStudio, but I can only see the shinytest controls. The left side, which should show my app, is blank. Perhaps this is an RStudio Viewer bug, maybe iframes are not supported?

Whatever the case may be, I have to open the app in an external browser to be able to use shinytest. So it might be a good idea to either fix that bug or force the app to open externally.

**Comment by wch** [comment]
What option are you setting to get your current behavior?

**Comment by daattali** [comment]
![image](https://user-images.githubusercontent.com/952340/29046803-1039996c-7b97-11e7-8ce9-6b5c93f1402b.png)

**Comment by hadley** [comment]
Is there some existing way to control this with `runApp()` and rstudioapi?  If not, this is probably out of scope for shinytest.

**Comment by daattali** [comment]
Yes there is.

```
runApp(launch.browser = TRUE)
```

Will launch in the browser regardless of the RStudio settings

**Comment by hadley** [comment]
Ah but that will force it to open in the external browser, which will be a behaviour change for people who haven't changed the default opening location.

**Comment by daattali** [comment]
Correct. Forcing opening in the external browser is exactly the point of this issue - because it seems to not work (at least in my OS, I can't speak for others OS) when not in a browser. Features not a bug 👍

**Comment by hadley** [comment]
Are you saying it doesn't work for you when run "in window"?

**Comment by daattali** [comment]
It does work "in window". In fact, even when my settings are set to "Run External", it gets opened in a window, so something in shinytest is already overriding my settings.

- When I'm set to "Run in Viewer Pane", nothing happens  <-- **bad**
- When I'm set to "Run in Window", it runs in a window fine
- When I'm set to "Run External", it runs in a window fine <-- works, but not using my settings

So it looks like the bahviour is already being overridden in a case where it doesn't need to. So I don't see any reason not to keep overriding also in the case where it would be useful to.

**Comment by hadley** [comment]
I don't see anything being overridden in shinytest — https://github.com/rstudio/shinytest/blob/master/R/recorder.R#L101-L102. So given that probably affects relatively few people (certainly it doesn't seem like other people have noticed it) and it's going to be relatively fiddly to fix (i.e. if RStudio running [sniff the shiny viewer preference](https://github.com/rstudio/rstudioapi/issues/54) and then temporarily change it if needed), I think this is unlikely to rise to the top of our to do list. Are you interested in doing a PR?

**Comment by daattali** [comment]
Hmm I'd be too worried that any small change I make might have unintended consequences since I have 0 familiairity with the code in this package. I'd rather not touch anything here

**Comment by hadley** [comment]
Ok, in that case, since you're the only person currently affected by the issue, I'm going to close it. If more people hit it, we can certainly consider investing our development time in the future.
