### ISSUE TITLE
Make the recording controls buttons visually

### ISSUE THREAD

**Issue by daattali** [rstudio/shinytest#118]
In the test recording app, the top right section is the controls (which look infinitely better than they did 6 months ago!)

They look a bit strange and unintuitive though because none of them look like clickable buttons, they all look like just icons and inline text. 

![image](https://user-images.githubusercontent.com/952340/28998980-1bd65ae0-7a06-11e7-84b5-563bff3ca151.png)

**Comment by wch** [comment]
I understand the concern, but a future goal is to have it integrate more nicely with the RStudio IDE, and this was designed to look have a look that was consistent with the IDE.
