### ISSUE TITLE
Any way to record user interactions that are not direct actions to a shiny input/output?

### ISSUE THREAD

**Issue by daattali** [rstudio/shinytest#119]
For example, if I have a text input and a submit button, and I have custom javascript that detects the "Return" keypress and clicks on the button, is there any way to capture the keypress with shinytest?

**Comment by wch** [comment]
There's not a way to record those actions. At the moment, I think you would have to use the webdriver interface to control the browser directly.

With your `app` object, you can currently access the webdriver object like this:

```R
web <- app$.__enclos_env__$private$web
```

And then with that you should be able to do something like:

```R
library(webdriver)
el <- web$findElement(css = "#someid")
el$sendKeys(key$enter)
```

The webdriver Session object currently a private property of the ShinyDriver class, but I think it may make sense to make it public.
