### ISSUE TITLE
Should have result viewer

### ISSUE THREAD

**Issue by wch** [rstudio/shinytest#124]
It would be useful to have results viewer, similar to the diff viewer, but which can look at the results of a single test.

**Comment by cpsievert** [comment]
Perhaps the listviewer package fits a portion of the bill? You can even copy/paste portions of the json spec:

```r
tmp <- tempfile(fileext = ".json")
json <- download.file(
  "https://raw.githubusercontent.com/rstudio/shinytest/master/tests/testthat/recorded_tests/rmd/tests/mytest-expected/001.json",
  tmp
)
listviewer::reactjson(jsonlite::fromJSON(tmp))
```

<img width="414" alt="screen shot 2019-01-30 at 11 38 28 am" src="https://user-images.githubusercontent.com/1365941/52000797-96c02000-2483-11e9-88c0-d192b2f22c2c.png">

**Comment by hadley** [comment]
I'm going to close this in recognition that this is unlikely to ever happen — the snapshotting functions in testthat have been designed to make this easier to do using existing tools, and we'll also have an improved diff viewer. I think that means it's unlikely that duplicating the effort specifically for shinytest will be worthwhile, but please re-open if you disagree.
