### ISSUE TITLE
Should show line numbers when setInput times out

### ISSUE THREAD

**Issue by wch** [rstudio/shinytest#127]
For example, if it times out, it currently prints this:
```
setInputs(app$setInputs(dynamic = "option2")): Server did not update any output values within 3 seconds. If this is expected, use `wait_=FALSE, values_=FALSE`, or increase the value of timeout_.
```

It would be helpful to have a line number. See the following for code to extract it:
  https://gist.github.com/wch/6562f61e0033c6890d2c0bd5852dd1a9
  https://github.com/rstudio/shiny/blob/4f3d26c/R/conditions.R

**Comment by hadley** [comment]
`rlang::trace_back()` is now an easy way to get this info.

**Comment by hadley** [comment]
Or you can use `withCallingHandlers()` + `cnd_entrace()`:

``` r
library(rlang)

f <- function() g()
g <- function() h()
h <- function() message("foo")
foo <- NULL
withCallingHandlers(message = function(cnd) foo <<- rlang::cnd_entrace(cnd), f())
#> foo
foo$trace
#>     █
#>  1. ├─base::withCallingHandlers(...)
#>  2. └─global::f()
#>  3.   └─global::g()
#>  4.     └─global::h()
```

<sup>Created on 2020-08-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Probably makes sense to provide a wrapper around `message()`/`inform()` for this case, so that any messages in shinytest clearly display where they're coming from.

**Comment by hadley** [comment]
Needs #338 first
