### ISSUE TITLE
After quitting from the app using the button, there should be a success message 

### ISSUE THREAD

**Issue by daattali** [rstudio/shinytest#130]
Every time I click "quit" and the entire page just grays out but nothing else happens, I keep thinking something broke. It would be useful to have some feedback message just to let the user know they successfully stopped the app and that they can return to rstudio now to view the test.

This is especially important when it asks me "Overwrite mytest.R?" and after I click yes the screen grays out - it isn't clear that the overwriting was complete and that I can proceed.

**Comment by wch** [comment]
What version of RStudio are you using? On my computer (Mac with RStudio 1.1.374), the window disappears immediately instead of graying out.

**Comment by daattali** [comment]
It's 1.0.153 on Win7. It's possible it's fixed on newer versions

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by wch** [comment]
The window also disappears immediately for me in RStudio 1.1.299 on Windows. I'm going to close since this is relatively minor and we'll recommend that people use a recent version of RStudio.
