### ISSUE TITLE
Diff tool only semi-work in RStudio Viewer 

### ISSUE THREAD

**Issue by daattali** [rstudio/shinytest#133]
I'm not sure if the diff app is supposed to work fully in rstudio or not. If not - then maybe browser should be enforced like #117 

Under Win 7 RStudio 1.0.153, I noticed a few problems:

- there is no vertical scrollbar
- the hyperlinks at the top that link to the different files don't work
- the "MODIFIED"/"ADDED"/etc labels for images take up an entire row

![image](https://user-images.githubusercontent.com/952340/30189231-866a18b0-93e7-11e7-9aee-3dec2901560d.png)

**Comment by wch** [comment]
I've fixed an issue where image diffs didn't display properly, in f26958b (tested on RStudio 1.1.299 in Windows).

Looks like I closed the issue too early, though, since there the other display issues are still present.
