### ISSUE TITLE
Enhancement: remember the user's parameter selections

### ISSUE THREAD

**Issue by daattali** [rstudio/shinytest#134]
In the testing app, there are two options "Open script in editor on exit" and "Run test script on exit"

I feel like people will generally prefer to have these settings persist, not have to click on them each time. Even a lightweight solution like using html5 local storage or a cookie could be enough to work for most people

**Comment by hadley** [comment]
Given the development resources available for shinytest, I think that this is unlikely to be implemented. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
