### ISSUE TITLE
After quitting from the recording app, don't open a new tab in rstudio if it's already open

### ISSUE THREAD

**Issue by daattali** [rstudio/shinytest#138]
When I call `recordTest()` several times in a row with the same default filename, every time I close it, a new tab is opened in rstudio. The result is that I have the same file open many times in rstudio. I don't know if the rstudio api allows you to view what file locations are already open in other tabs, so maybe you can't do this, but it'd be nice to avoid this behaviour

**Comment by wch** [comment]
I think this is fixed in newer versions of RStudio.
