### ISSUE TITLE
Error in base64 decode

### ISSUE THREAD

**Issue by fabianekc** [rstudio/shinytest#143]
Testing my shiny app does not produce any output in tests/mytest-current/ and fails with:

> Running mytest.R Error in jsonlite::base64_dec(dat) : Error in base64 decode

here is my `mytest.R`

    app <- ShinyDriver$new("../")
    app$snapshotInit("mytest")

    app$snapshot()

Do you have any recommendations how to debug this error?

Some information about my environment:
- macOS 10.12.6
- R version 3.3.3 (2017-03-06)
- RStudio 1.0.143
- shiny 1.0.5
- shinytest 1.2
- jsonlite 1.5

Please let me know if you need any additional information!

**Comment by wch** [comment]
Hm, it's probably happening here:
https://github.com/rstudio/shinytest/blob/dab6c3701b740ca3ec94fb6ad8b547e44cf08bce/R/snapshot.R#L307

You could set `options(error=recover)` and then check the value of `dat` when the error occurs. But I think there may well be `tryCatch` wrapping the code; if that's right, then this won't work. Then the best bet would be to clone this repository, put a `browser()` statement right above that line, install the package, and test it.

If that all sounds like too much, you could wait for us to address it. If you could provide a reproducible example, that would help.

**Comment by fabianekc** [comment]
I was able to get the value of `dat` using `options(error=recover)` and it seems that `dat` is not a valid base64 encoded string. `dat` ends with `...rkJggg==\\\"` - the double quotes are part of the string. Maybe a problem with escaping?

I also cloned the repository and used the shinytest package locally. However, with the same shiny app it produced a different error:

    Running mytest.R Error: lexical error: probable comment found in input text, comments are not 
    enabled.
              489dd46d0fe6c8b1ae4963a5cc03]"/>\n  OwnYourData\n<\/div>",  
                         (right here) ------^

Let me know if you have any ideas. Meanwhile, I try to create a reproducible example but this will take some time. I'm in the process of splitting this shiny app into modules and parts are now in a separate R-package. Removing things will take me a few days.

**Comment by wch** [comment]
Hm, could you write `dat` out to a file and attach it here? Does the image show up properly in your browser?

Still, the code that calls `base64_dec` probably should be wrapped in a `tryCatch`, so that errors don't stop the tests.

Based on the two errors that you've mentioned, my guess is that something is wrong with the JSON encoding or decoding. If you do `debug(shinytest:::hash_snapshot_image_data)`, it will drop you into a debugger prompt at the top of the function. At that point, run this to save it to a file:

```R
writeLines(data, "data.json")
```

Then you can type `c` and enter to continue running the code.

**Comment by fabianekc** [comment]
Here the attachment with ´debug(shinytest:::hash_snapshot_image_data)´ before running ´testApp´: [data2.json.txt](https://github.com/rstudio/shinytest/files/1326482/data2.json.txt)

Also attached the output from ´writeLines(dat, "data.json.txt")´ in the function that fails:
 [data.json.txt](https://github.com/rstudio/shinytest/files/1326475/data.json.txt)

And I don't get any output (PNG or JSON) in test-current or test-expected (but it works for me in a simple shiny app I took from http://shiny.rstudio.com/gallery/kmeans-example.html)

**Comment by wch** [comment]
It looks you have some dynamic UI (`oyd-hdrMyAppsLink`) that has a `img` tag with embedded data. Is that correct?

Here's an app that does something similar:

```R
shinyApp(
  fluidPage(
    htmlOutput("image")
  ),
  function(input, output) {
    output$image <- renderUI({
      img(src = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAJ0lEQVQoU2Ps6Oj4z4AGXFxc0IUYGIeCwjNnzmB4Zs+ePZieGQIKAZKhLO1oE8Z/AAAAAElFTkSuQmCC")
    })
  }
)
```

The problem is that shinytest is incorrectly identifying that that as an image it should hash.

**Comment by fabianekc** [comment]
Yes, you are right. I removed the dynamic image and the test runs successfully.

Thanks!
