### ISSUE TITLE
recordTest() should capture and print errors from Shiny process

### ISSUE THREAD

**Issue by wch** [rstudio/shinytest#146]
When running `recordTest()` it's possible for the Shiny process to throw warnings and errors. In some cases, the app will start in the user's regular R session, but fail to start when launched with `recordTest()`, possibly due to user customizations of `.Rprofile`. See #114 for an example.

The recorder app should display these errors, or they should be captured and displayed at the R console on exit.

**Comment by KZARCA** [comment]
I get the same issue as #114, would be very helpful
