### ISSUE TITLE
Provide shims for dependency installation

### ISSUE THREAD

**Issue by jmcphers** [rstudio/shinytest#154]
Currently it's not possible to know whether shinytest's dependencies are present without making presumptions about what those dependencies are. As its dependencies may change in the future (e.g. moving from phantomjs to headless Chrome), this makes it somewhat difficult to front-load the dependencies. 

To facilitate IDE integration, we'd like to propose two additional public methods (naming TBD):

`unsatisfiedDependencies` -- returns a list of software (a character vector) which needs to be installed for `shinytest` to operate

`installDependencies` -- accepts a character vector of software to install, and attempts to install it

**Comment by wch** [comment]
This was done in #179 (though the implementation isn't exactly as described here).
