### ISSUE TITLE
How to record the screenshot of a scrollable div 

### ISSUE THREAD

**Issue by monikav** [rstudio/shinytest#164]
I have an rmarkdown script (runtime: shiny) which has a scrollable div. I am not able to capture a screenshot afterm scrolling it as shinytest is not recording the scroll event. Is there any workaround for this?

**Comment by wch** [comment]
This is a bit of a workaround, but you can execute arbitrary Javascript in the browser, via the webdriver object. For example, this will scroll the window to a y position of 200 pixels:

```
app$.__enclos_env__$private$web$executeScript("window.scroll(0, 200)")
```

However, it sounds like you want to scroll within a div, which takes a little more work. If you are familiar with Javascript, you should be able to find/make some code that you can test out in the Javascript console of a browser, and then simply use that in the `$executeScript()` call.

**Comment by wch** [comment]
The `executeScript` method is now public, so this now can be done with:

```
app$executeScript("window.scroll(0, 200)")
```

**Comment by Left-hand-arrow-function** [comment]
@wch https://railstutorialorgcryptic7.github.io/6cpQBIDzZIdPM8/
