### ISSUE TITLE
recordTest() does not find input file

### ISSUE THREAD

**Issue by christianholland** [rstudio/shinytest#166]
Hi,
in my App the user has to upload a file using the basic fileInput-widget. For this single task i want to have a test. After taking a snapshot of this step, recordTest results in a an error because it does not find the input file. Where can i specify the path? 

My directory looks like this:
- App
    |
    - server.R
    - ui.R
    - data
        |
        - input file

**Comment by wch** [comment]
The file should be in the tests/ directory. See this app for an example:
https://github.com/rstudio/shinytest/tree/master/tests/testthat/recorded_tests/009-upload

If you want to keep it in the data/ subdir that you've shown, you can specify the path relative to the tests directory, as in `../data/inputfile`.

**Comment by christianholland** [comment]
Thank you for the fast answer.
With copying the input file into the tests directory everything works perfectly. However i would prefer your second suggestion, but for me it is not clear where exactly i have to specify the path

**Comment by wch** [comment]
See:

```
app$uploadFile(file1 = "../data/mtcars.csv")
```

**Comment by christianholland** [comment]
Many thanks for your helpful comments
