### ISSUE TITLE
difference between expected and current when using plotly (elementId)

### ISSUE THREAD

**Issue by emrichter** [rstudio/shinytest#174]
Hi
I'm testing a simpe shiny app with a plotly-figure. Since plotly always generates a new elementId for its plots, shinytest shows this as a difference between expected and current results. In my case (and I guess also in general) this should not count as a real difference though, since nothing has changed.
Is there a way to ignore this?

![grafik](https://user-images.githubusercontent.com/36728688/36587184-a89e1658-1884-11e8-8890-d1fe3f76d385.png)

**Comment by floswald** [comment]
same issue

**Comment by Jax89** [comment]
Just started testing my app, really like the test tool but facing the same issue

**Comment by floswald** [comment]
For me it’s just to not test plotly elements at all. Standing by for a
better solution

**Comment by clabornd** [comment]
I am currently running a janky solution which involves exporting parts of the plotly object that don't depend on the element ID.

in server.R:  
`p <- plot_ly(...)`
`exportTestValues(plot_attrs = p$x$attrs[[p$x$cur_data]])`

in test_script.R:  `app$snapshot(items = list(export = "plot_attrs"))`

Not sure how much this is _really_ testing anything.

**Comment by wch** [comment]
FYI: it's possible to call `snapshotPreprocessOutput()` to add an output preprocessing function to clean up the raw output value to something that's more deterministic for testing. See:
https://github.com/rstudio/shiny/blob/6ede019/R/snapshot.R#L10-L19

For an example of usage, see: https://github.com/rstudio/DT/blob/80981d3/R/shiny.R#L116-L124

**Comment by hadley** [comment]
Fixed in plotly.
