### ISSUE TITLE
Consider better error message when phantomjs is not isntalled

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/shinytest#175]
When phantomjs is not installed `recordTest()` triggered:

```
> recordTest("test/")
Error in process_get_error_connection(self, private) : 
  stderr is not a pipe.
```

Running `webdriver::install_phantomjs()` solves this issue.

However, I wonder if we should consider to explicitly check if phantomjs is installed in `shinytest` and if not, trigger a nice error message prompting user to install this. As a user, I would prefer to have a `shinytest_install()` helper function since, ideally, I wouldn't even need to know what the `webdriver` project is.

**Comment by wch** [comment]
It now gives the following message:

```
> recordTest()
shinytest requires a headless web browser (PhantomJS) to record and run tests.
To install it, run shinytest::installDependencies()
If it is installed, please make sure the phantomjs executable can be found via the PATH variable.
Error in sd_initialize(self, private, path, loadTimeout, checkNames, debug,  : 
  PhantomJS not found.
```
