### ISSUE TITLE
sd_startShiny: shinytest defaults to random port

### ISSUE THREAD

**Issue by horowitza** [rstudio/shinytest#177]
In some applications, the user may need to specify the port which shinytest runs on, however shinytest uses `random_open_port()` to specify the port.

```
  port <- random_open_port()
  if (is_rmd(path)) {
    # Shiny document
    rcmd <- paste0(
      rcmd,
      "; options(shiny.testmode = TRUE); ",
      sprintf("rmarkdown::run('%s', shiny_args=list(port=%d))", path, port)
    )
  } else {
    # Normal shiny app
    rcmd <- paste0(
      rcmd,
      "; options(shiny.testmode = TRUE); ",
      sprintf("shiny::runApp('%s', port=%d)", path, port)
    )
  }
```
https://github.com/rstudio/shinytest/blob/master/R/initialize.R#L101-L116

**Comment by wch** [comment]
You can now do the following:

```R
recordTest('app/', shinyOptions = list(port=8000))
```


The result is that this goes at the top of the test script:

```R
app <- ShinyDriver$new("../", shinyOptions = list(port=8000))
```

If you have existing test scripts, you can modify them with the `shinyOptions` parameter.
