### ISSUE TITLE
Need to figure out how to not include test results in packages

### ISSUE THREAD

**Issue by wch** [rstudio/shinytest#185]
In the [package documentation](https://rstudio.github.io/shinytest/articles/package.html), it would be good to not include the test results in inst/ as part of the built package. However, the tests won't work if the tests/ directory for an app is in .Rbuildignore. 

The documentation about .Rbuildignore was originally in the package docs, but was removed in 983c258.

**Comment by hadley** [comment]
Duplicate of #140
