### ISSUE TITLE
Request: future testing support for shiny.js-only apps

### ISSUE THREAD

**Issue by pzingg** [rstudio/shinytest#186]
We have built a shiny app that does not use "native" shiny input or output bindings, but instead uses shiny.js functionality to send data between UI and server, as in [this article](https://ryouready.wordpress.com/2013/11/20/sending-data-from-client-to-server-and-back-using-shiny). 

The only communications are from the UI, via `Shiny.onInputChange()`, and from the server side using `session$sendCustomMessage()`. We have no "outputs", but we could use the shinytest "export" feature to test the state of the application in snapshots.

It would be nice to be able to interact with shiny test using `app$setInputs(...)`, but of course when I manually try to add some of those to a test script, I get `Unable to find input binding for element`. Is there a way to "prime" shinytest to set up bindings for specified named inputs when the test script starts, so that we could later use `app$setInputs(...)` to pump data into the backend?

**Comment by michaelhogersosis** [comment]
@rpodcast, one way is as follows,

In your front-end you might use:
`<button onclick="Shiny.setInputValue('exampleButton', {value1: true, value2: 'string'})" class="btn action-button">Example</button>
<h5 id="exampleHeader"></h5>
`


`observeEvent(input$exampleButton, {
if (input$exampleButton$value1){
  shinyjs::html(id="exampleHeader", 
                       input$exampleButton$string)
}
})`

Bit of an odd example perhaps, but this uses no shiny-bound-input class, nor an output class.
