### ISSUE TITLE
Request: Option to ignore certain files when running snapshotCompare()

### ISSUE THREAD

**Issue by rpodcast** [rstudio/shinytest#188]
I am using shinytest within an application that lets the user download a powerpoint slide deck (produced by [`officer`](https://davidgohel.github.io/officer/)).  Part of my tests involve making sure the download functionality of the slides is working.  I have the following line in my test script to trigger a download (`download_slides` is the `outputId` of the download button):

```r
app$snapshotDownload("download_slides", filename = "test_slide_download.pptx")
```

The test script runs successfully, but one quirk of these exported powerpoint files is the file sizes can differ from one test run to another even though the actual content inside them is the same (that's a separate issue).  When the test run is being compared to the expected results, differences are detected in the exported files (and not the JSON) as seen in this output:

```
tmp <- testApp(".", "test-app.R", compareImages = FALSE, interactive = FALSE)
Running test-app.R 
==== Comparing test-app
  Differences detected between test-app-current/ and test-app-expected/:

    Name                        Status      
    002.json                    No change   
    test_slide_download.pptx != Files differ

To view a textual diff, run:
  viewTestDiff(".", interactive = FALSE)
```

In any event, I don't want the `.pptx` files to be compared when running `snapshotCompare`, as I will flag key reactive objects that have the textual content of the slides using `shiny::exportTestValues` so they can be compared easily alongside the inputs and outputs.  I know that images can be excluded via the `images = FALSE` flag, and I wondered if there was a way we could supply an optional vector of file names that could also be excluded when running `snapshotCompare`?

**Comment by sjspielman** [comment]
+1 Here. Similar issues exist for, as an example, interactive networks where coordinates can regularly change, but not problematically, when stochastic algorithms specify node layout positions. An option to ignore certain inputs would be fantastic to get around this and similar cases!

**Comment by jcheng5** [comment]
@sjspielman Do you mean "ignore certain _outputs_"? I think @rpodcast and your ideas both make a lot of sense. I do struggle to think of how we would ignore the differences for specific outputs when comparing PNG snapshots though.

**Comment by sjspielman** [comment]
Hi @jcheng5 , woops! Yes, of course "outputs." A good option for this type of case might be to allow users to specify certain json fields that have no bearing on testing behavior. Would there be a possible option (which could be discouraged for the majority of use cases) to ignore png snapshots when diff'ing expected from current?

**Comment by jcheng5** [comment]
There's currently an `images` parameter in `snapshotCompare` that you can set to `FALSE`, does that sound like what you want?

**Comment by jcheng5** [comment]
Oh or `testApp`'s `compareImages` parameter

**Comment by rpodcast** [comment]
@jcheng5 in my case my app is producing an artifact (powerpoint file) so it's not necessarily an output in the traditional shiny sense.  My ideal situation is to have `shinytest` either straight up ignore the file altogether, or just send an error if the artifact was not created from the download button, which would certainly be an error I'd want to be notified about.

**Comment by sjspielman** [comment]
@jcheng5 Definitely, thanks, that should help for the png component.

**Comment by jcheng5** [comment]
@rpodcast Yep, makes sense. @wch is out sick, maybe he can weigh in when he's back.

**Comment by hadley** [comment]
Over a year later, I think it's now more clear that the resolution for this sort of issue is to move to hand-rolled tests where you control precisely what is compared. #260 will also help with the problem of controlling exactly what you take a screenshot of.

**Comment by beansrowning** [comment]
@rpodcast Do you have any wisdom to share on this? It seems like there was never a good solution proposed, and my use case is almost identical.
