### ISSUE TITLE
Error in sd_getAllValues(self, private, input, output, export) 

### ISSUE THREAD

**Issue by shalutiwari** [rstudio/shinytest#192]
```R
recordTest('107-events',shinyOptions = list(display.mode="normal"))
```

```
Listening on http://127.0.0.1:4701
Saved test code to /Users/shalutiwari/shiny-examples-branch/shiny-examples/107-events/tests/mytest.R
Running mytest.R setInputs(app$setInputs(end = "click")): Server did not update any output values within 3 seconds. If this is expected, use `wait_=FALSE, values_=FALSE`, or increase the value of timeout_.
Error in sd_getAllValues(self, private, input, output, export) :
 Unable to fetch all values from server. Is target app running with options(shiny.testmode=TRUE?)
```

```R
app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(color1 = "click")
app$snapshot()
app$setInputs(message = "click")
app$setInputs(message = "click")
app$snapshot()
app$setInputs(busy = "click")
app$snapshot()
app$setInputs(end = "click")
app$snapshot()
```

**Comment by wjtimmerman** [comment]
For anyone searching for this error later (or @shalutiwari ), I sometimes get this error when I lose internet connectivity (my shiny apps rely on some GET requests) or when my laptop goes to sleep during a set of tests -- addressing those may fix this for you. Appears this error triggers when anything but HTTP status code 200 is not received: https://github.com/rstudio/shinytest/blob/master/R/app-get-all-values.R

**Comment by ariayi** [comment]
@wch 
get the same error message too. 

This happens when I use shinytest on R connect..same code works on local Rstudio though..
>             app$setInputs(run = "click")
setInputs(app$setInputs(run = "click")): Server did not update any output values within 3 seconds. If this is expected, use `wait_=FALSE, values_=FALSE`, or increase the value of timeout_.
Error in sd_getAllValues(self, private, input, output, export) : 
  Unable to fetch all values from server. Is target app running with options(shiny.testmode=TRUE?)

**Comment by LukasK13** [comment]
Any updates on this?

**Comment by LukasK13** [comment]
I can confirm, this error happens when the shiny app crashes in the background process. So debugging the shiny app fixed the "bug" in shinytest for me.

**Comment by alexvpickering** [comment]
I get the same error, app doesn't crash. Running in Rstudio.

**Comment by alexvpickering** [comment]
I think I found the culprit for my app. Here is how I debugged it:

```R
library(shinytest)
app <- ShinyDriver$new("inst/app", loadTimeout = 20000)
app$snapshotInit("mytest")

# this initially didn't work
app$snapshot()

# get all inputs, outputs, and exported values
vals <- app$listWidgets()

# for me, the culprit was an output
# loop through all output values, print each, and try selective snapshot
for(val in vals$output) {
  print(val)
  app$snapshot(items = list(output = val))
}
...
[1] "datasets-cells_plotly-plotly"
Error: lexical error: invalid char in json text.
                                       ERROR: lexical error: invalid c
                     (right here) ------^

```

After identifying the culprit output, I modified its output value as described [here](https://rstudio.github.io/shinytest/articles/faq.html#can-i-modify-the-output-and-input-values-that-are-recorded-in-snapshots).

Not sure why this particular plotly output caused issues as it renders fine (I have a few others in the app as well that cause no issues).

**Comment by rfaelens** [comment]
The issue arises from using `shiny::req` or any other silent error function in combination with `plotly`. See https://github.com/ropensci/plotly/issues/1685 for more information.

**Comment by hadley** [comment]
Reprex:

```R
path <- "../shiny-examples/107-events"
dir.create(file.path(path, "tests", "shinytest"), recursive = TRUE)
writeLines(con = file.path(path, "tests", "shinytest", "mytest.R"),  '
app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(color1 = "click")
app$snapshot()
app$setInputs(message = "click")
app$setInputs(message = "click")
app$snapshot()
app$setInputs(busy = "click")
app$snapshot()
app$setInputs(end = "click")
app$snapshot()
')
shinytest::testApp(path)
```

I think two fixes are needed in `sd_getAllValues()`:

* It should use a more robust technique to confirm that `httr::GET()` has succeeded, and to bubble the error up to the user

* The hint is wrong: in most cases it's not that the app hasn't been started correctly, but has stopped or is otherwise busy.

**Comment by hadley** [comment]
Minimal reprex:

```R
library(shinytest)
app <- ShinyDriver$new("../shiny-examples/107-events")
app$setInputs(end = "click")
```
