### ISSUE TITLE
Shinytest failing on Travis, passing locally

### ISSUE THREAD

**Issue by GShotwell** [rstudio/shinytest#198]
I have a shiny gadget which is being tested as part of a package. The app is packaged in a  [function](https://github.com/Crunch-io/crunchy/blob/900313a0c29ee04bab5da8d5fca2532a31e1d83d/R/gadgets.R#L30) and tested using [this test app](https://github.com/Crunch-io/crunchy/blob/shinytest/tests/testthat/gadgets/makeArrayGadget/app.R). This app includes a bit of code to make use of httptest mocks. 

The issue is that everything passes when I run CMD check locally, and on Appveyor, but I'm getting errors on Travis. In particular: 

```
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  >     "tabstrip": "Select Subvariables",
  diff /tmp/RtmpKcyhKP/shinytest-diff-297d47d0beb9/mytest-expected/003.json /tmp/RtmpKcyhKP/shinytest-diff-297d47d0beb9/mytest-current/003.json
  14a15
  >     "tabstrip": "Select Subvariables",
  diff /tmp/RtmpKcyhKP/shinytest-diff-297d47d0beb9/mytest-expected/004.json /tmp/RtmpKcyhKP/shinytest-diff-297d47d0beb9/mytest-current/004.json
  11a12
  >     "tabstrip": "Select Subvariables",
```

It appears that what's happening is that the output from the Travis app includes a `tabstrip` element which wasn't recorded by the shinytest recorder. The app does have a `minitabstrip` panel, but the  recorded doesn't seem to recognize that component, and so no tabstrip is included in the app output. 

Some of the things I've verified: 

- Travis and my local setup are on the same version of shinytest (`rstudio/shinytest@7f2b6a6`). 
- A recorded test that includes just the single snapshot and no interaction also generates the same behaviour
- I don't see anything in the printed shinytest object that jumps out as being strange

Do you have any ideas of what I should look into next to figure out how to resolve this issue? Is there a way to get more information from Travis about the difference between the expected output and the actual output or to reproduce this issue locally?

**Comment by hadley** [comment]
Cross-platform testing is extraordinarily difficult so be prepared for frustration 😄 We are working on more general tools in testthat 3.0.0 that should help with this (particularly in giving more informative output), but unfortunately I don't think there's much we can do in shinytest at the moment.
