### ISSUE TITLE
The command "R -f run_tests.R" exited with 2.

### ISSUE THREAD

**Issue by walefmachado** [rstudio/shinytest#200]
Hello

I'm using the `shinytest` with continuous integration on Travis CI. When I run the build I get this error:
```

0.02s$ R -f run_tests.R
Fatal error: cannot open file 'run_tests.R': No such file or directory
The command "R -f run_tests.R" exited with 2.
```

but the` run_tests.R` file is in my repository

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
