### ISSUE TITLE
Cannot find shiny port number while running testApp()

### ISSUE THREAD

**Issue by GonzaloXavier** [rstudio/shinytest#202]
Like #111 I get this same error and Suppressing the package startup messages did not work. I do have all in an app.R instead of the separate structure. recordTest() does not timeout, however, testApp() does.

**Comment by 1beb** [comment]
@GonzaloXavier please provide a traceback() and specify the timeouts that you tested.

**Comment by GonzaloXavier** [comment]
Traceback

```13.
stop("Cannot find shiny port number. Error:\n", paste(err_lines, 
    collapse = "\n")) at initialize.R#149
12.
sd_startShiny(self, private, path, seed, loadTimeout, shinyOptions) at shiny-driver.R#366
11.
private$startShiny(path, seed, loadTimeout, shinyOptions) at initialize.R#27
10.
sd_initialize(self, private, path, loadTimeout, checkNames, debug, 
    phantomTimeout = phantomTimeout, seed = seed, cleanLogs = cleanLogs, 
    shinyOptions = shinyOptions) at shiny-driver.R#209
9.
.subset2(public_bind_env, "initialize")(...) 
8.
ShinyDriver$new("../") at mytest.R#1
7.
eval(expr, envir, enclos) 
6.
eval(ei, envir) 
5.
withVisible(eval(ei, envir)) 
4.
source(testname, local = env) at test-app.R#88
3.
FUN(X[[i]], ...) 
2.
lapply(found_testnames, function(testname) {
    withr::local_dir(testsDir)
    withr::local_envvar(c(RSTUDIO = ""))
    withr::local_options(list(shinytest.app.dir = "appdir")) ... at test-app.R#72
1.
testApp() 
```

**Comment by cderv** [comment]
@GonzaloXavier did you try the `loadTimeout` argument in `recordTest` ? 
Increasing it worked for me : `recordTest(..., loadTimeout=100000)`

**Comment by GonzaloXavier** [comment]
> @GonzaloXavier did you try the `loadTimeout` argument in `recordTest` ?
> Increasing it worked for me : `recordTest(..., loadTimeout=100000)`

The issue here was `testApp` and not `recordTest`. This was a while ago but I think I had to re write the `testApp()` function in order to have a working `loadTimeout` argument.

**Comment by cderv** [comment]
The issue with `recordTest` was happening after the recording when the test was running. `recordTest` runs `testApp` interally. I think the `loadTimeout` argument in `recordTest` is for creating one inside the test file. I got
```r
app <- ShinyDriver$new("../", loadTimeout = 1e+05, seed = 1234)
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(student = "6")
app$snapshot()
```` 

Ans with a `loadTimeout` in `ShinyDriver$new` the `testApp` call does not throw an error. 

This is why I thought it was related.

**Comment by 1beb** [comment]
@cderv thanks, this is still on a list of things to do for us. Will update here when we get around to the tests again using your recommended adjustment.

**Comment by hadley** [comment]
Now tracking in #329
