### ISSUE TITLE
setInputs documentation should have wait_=FALSE, values_=FALSE

### ISSUE THREAD

**Issue by dmenne** [rstudio/shinytest#204]
`Server did not update any output values within 3 seconds. If this is expected, use `wait_=FALSE, values_=FALSE`, or increase the value of timeout_.`

When I got this message, I had to dig through the full documentation to find the parameter described in FAQ only. It is not clear that these are parameters of `setInputs`, since nothing is in the reference

**Comment by hadley** [comment]
Fixed in b9e2c7d06cd2a542777d27c648c356b0b6ef9f78
