### ISSUE TITLE
Using shinytest to select menuSubItem in shinydashboard app

### ISSUE THREAD

**Issue by alastairrushworth** [rstudio/shinytest#205]
I am trying to use `shinytest` to simulate the following user action within an app built on `shinydashboard`:

- user clicks on a sidebar `menuItem` which expands to reveal a number of `menuSubItem`
- user clicks on a sidebar `menuSubItem` which should update the tab shown in `dashboardBody`

The code below illustrates how such an app might look.  The problem is that when `recordTest(".")` is run for this app and the steps above are followed, the test script returned doesn't contain any reference to user selection of `menuSubItems`:

```
app <- ShinyDriver$new("../")
app$snapshotInit("mytest")
app$setInputs(sidebarCollapsed = FALSE)
app$setInputs(sidebarItemExpanded = "Widgets")
app$snapshot()
```

This seems related to issue #167 which has been marked as closed, but I'm still unable to resolve the problem above.  I'm using the dev versions of both `shinydashboard` and `shinytest`.

```
library(shiny)
library(shinydashboard)

ui <- dashboardPage(
  dashboardHeader(title = "Basic dashboard"),
  ## Sidebar content
  dashboardSidebar(
    sidebarMenu(
      menuItem("Widgets", tabName = "widgets", icon = icon("globe"),
               menuSubItem("Widget1", tabName = "widget1", icon = icon("blind")), 
               menuSubItem("Widget2", tabName = "widget2", icon = icon("blind")))
    )
  ),
  ## Body content
  dashboardBody(
    tabItems(
      # Second tab content
      tabItem(tabName = "widget1", h2("Widgets1 tab content")),
      # Second tab content
      tabItem(tabName = "widget2", h2("Widgets2 tab content"))
    )
  )
)

server <- function(input, output){}
shinyApp(ui, server)
```

**Comment by cpsievert** [comment]
It seems as though if you add an `id` to `sidebarMenu()`, then shinytest will in fact record the user clicks on the menu items.

@wch would it make sense to include an id, by default?

**Comment by wch** [comment]
Note that the answer to this question is in https://rstudio.github.io/shinydashboard/behavior.html#bookmarking
