### ISSUE TITLE
Warning: Error in gsub: input string 1 is invalid UTF-8

### ISSUE THREAD

**Issue by PieterMaertens** [rstudio/shinytest#206]
When recording a test with the shinytest package using recordTest(), everything works fine.
But when I rerun the test with the following statement:
testApp(".")
I get an error message:
Warning: Error in gsub: input string 1 is invalid UTF-8
The encoding of all shiny files (global.R, server.R and ui.R) is UTF-8. The ui + server files contain special characters.
I run the shinytest package 1.3.0 on a windows 10 pc with R version 3.5.0 and Rstudio version 1.1.453 and the test json file is:

{
  "input": {
    "action0": 0,
    "algemeen": "Herkomst",
    "bevolking": "Ja",
    "CMI": "Globaal",
    "CMIKeuze": "Alle",
    "jaren1": "2017",
    "jaren2": "2016",
    "jaren2T": "2016",
    "jaren3": "2017",
    "jaren3T": "2017",
    "jaren4": "2017",
    "jaren4T": "2017",
    "jaren5T": "2017",
    "jaren6": "2017",
    "jaren6T": "2017",
    "jaren7": "2017",
    "KenletterKeuze": "Alle",
    "kilometer": 5,
    "MA": "Globaal",
    "MID": "Globaal",
    "MIDVBL": "Globaal",
    "mzgJaren2": [
      2016,
      2017
    ],
    "NHPPD": "BB per Oper VTE",
    "niveau": "0",
    "show1": 0,
    "show18": 0,
    "show19": 0,
    "show2": 0,
    "show21": 0,
    "show3": 0,
    "show4": 0,
    "show40": 0,
    "show5": 0,
    "show6": 0,
    "show7": 0,
    "VBL": "Globaal",
    "ZR": "provincie"
  },
  "output": {
    "Contact2": "Uw contactpersoon is Test",
    "Disclaimer": "test",
    "herkomstTitel": "<h4 align=\"center\">**Herkomst patiënten**<\/h4>",
    "mymap": {
      "x": {
        "options": {
          "zoomControl": false
        }
      },
      "evals": [

      ],
      "jsHooks": [

      ],
      "deps": [

      ]
    },
    "semester1": {
      "html": "Opgelet: enkel 1ste semester!",
      "deps": [

      ]
    },
    "show": {
      "message": "",
      "call": "NULL",
      "type": [
        "shiny.silent.error",
        "validation"
      ]
    },
    "showdetails": {
      "message": "",
      "call": "NULL",
      "type": [
        "shiny.silent.error",
        "validation"
      ]
    },
    "tekstzkh": "test"
  },
  "export": {

  }
}

**Comment by zappingseb** [comment]
There is a pretty easy solution working under Linux & Mac OS:

https://stackoverflow.com/questions/29465612/how-to-detect-invalid-utf8-unicode-binary-in-a-text-file

I did it by

`sed s/\n/\\n/g 001.json > output002.json`

and

`grep -axv '.*' output002.json`

I got the lines of code that contain non-utf8 and removed them.

For me it was a JavaScript file I imported

**Comment by felipegerard** [comment]
I'm getting a similar error when comparing current results to expected ones. I also have non-ASCII characters in my code, but in my view the solution shouldn't be to just remove them. What if I need them for some filters for instance?

I found that if I manually open the JSON files as the correct encoding (ISO-8859-1 in my case) and overwrite them as UTF-8, the comparison works fine. Therefore the problem lies in the fact that the JSON files get saved as something different from UTF-8 but then get opened as UTF-8, which produces invalid characters.

**Comment by AlexandraKapp** [comment]
I think the problem is due to the `writeChar ` function, which does not work with non-ASCII characters.
Maybe this could be changed to jsonlite::write_json?

https://github.com/rstudio/shinytest/blob/0170c661c7c252fb20ff8e998a0ac3f1c50c0e08/R/snapshot.R#L54

**Comment by wch** [comment]
A few comments on this:

* A small reproducible example would be helpful.
* `writeChar` *does* work with non-ASCII characters. However, it writes them in the native encoding. On Mac/Linux, this is almost always UTF-8. On Windows, it is usually something else.

**Comment by AlexandraKapp** [comment]
Maybe this is only a propblem on Windows then?

On my windows PC, this error can be reproduced with the following example: 

1. run `shinyapps::recordTest()` on this example App

```R
library(shiny)

# Define UI for application that draws a histogram
ui <- fluidPage(

    # Application title
    titlePanel("Old Faithful Geyser Data"),

    # Sidebar with a slider input for number of bins 
    sidebarLayout(
        sidebarPanel(
            sliderInput("bins",
                        "Number of bins:",
                        min = 1,
                        max = 50,
                        value = 30)
        ),

        # Show a plot of the generated distribution
        mainPanel(
           plotOutput("distPlot")
        )
    )
)

# Define server logic required to draw a histogram
server <- function(input, output) {

    output$distPlot <- renderPlot({
        # generate bins based on input$bins from ui.R
        x    <- faithful[, 2]
        bins <- seq(min(x), max(x), length.out = input$bins + 1)
        
        

        # draw the histogram with the specified number of bins
        hist(x, breaks = bins, col = 'darkgray', border = 'white')
        
        exportTestValues(count_of_x = {length(x)}, test = "")
    })
}

# Run the application 
shinyApp(ui = ui, server = server)

```

2. add a non-utf8 character to the exportTestValues. 

```R

library(shiny)

# Define UI for application that draws a histogram
ui <- fluidPage(

    # Application title
    titlePanel("Old Faithful Geyser Data"),

    # Sidebar with a slider input for number of bins 
    sidebarLayout(
        sidebarPanel(
            sliderInput("bins",
                        "Number of bins:",
                        min = 1,
                        max = 50,
                        value = 30)
        ),

        # Show a plot of the generated distribution
        mainPanel(
           plotOutput("distPlot")
        )
    )
)

# Define server logic required to draw a histogram
server <- function(input, output) {

    output$distPlot <- renderPlot({
        # generate bins based on input$bins from ui.R
        x    <- faithful[, 2]
        bins <- seq(min(x), max(x), length.out = input$bins + 1)
        
        

        # draw the histogram with the specified number of bins
        hist(x, breaks = bins, col = 'darkgray', border = 'white')
        
        exportTestValues(count_of_x = {length(x)}, test = "ä@ü")
    })
}

# Run the application 
shinyApp(ui = ui, server = server)
```

3. now run `shinytest::testApp()` on this changed version. 

I then get this error: 

![grafik](https://user-images.githubusercontent.com/18367515/87154479-97382980-c2b9-11ea-812c-1b4aa158c039.png)

**Comment by wch** [comment]
FWIW, I made an example that reproduces the problem here: https://github.com/rstudio/shinycoreci-apps/pull/67/files

On a Mac, the JSON file is UTF-8, but on Windows it's ISO-8859 (or latin-1).
