### ISSUE TITLE
Feature request: initialize a shinyapp using a "shiny.appobj" object

### ISSUE THREAD

**Issue by daattali** [rstudio/shinytest#21]
When I test quick small shiny apps, I don't like to have to save a new file and then delete it, I prefer to just run some code in the console.  It'd be convenient to be able to do

```
library(shiny)
library(shinytest)

ui <- fluidPage(
  numericInput('num', "num", "5")
)

server <- function(input, output, session) {
  observe(cat(input$num))
}

app <- shinyapp$new(app = shinyApp(ui = ui, server = server))
```

**Comment by gaborcsardi** [comment]
:+1: Yes, thought about this. It is easy, basically we can just pass the argument(s) from `shinyapp$new` to `runApp`

**Comment by daattali** [comment]
So you mean it's already supported right now? Or it's easy for you to add?

**Comment by gaborcsardi** [comment]
Not supported now, sorry for the confusion. But I was aware of it, and yes, it is easy to fix.

**Comment by gaborcsardi** [comment]
It is actually not that trivial, because I start do `shiny::runApp()` in another R session. So I'll need to copy over the object(s), potentially together with their environment, etc.

But I'll try to make it work.

**Comment by daattali** [comment]
I don't think this makes sense anymore with the new direction the package took
