### ISSUE TITLE
Switching tabPanels does not fire specific event in recordTest

### ISSUE THREAD

**Issue by dmenne** [rstudio/shinytest#211]
TabSetPanel has an id, but tabPanel does not. So when I switch the panels under recordTest, I get a generic event from tabsetPanel (tabSet in the example below), but the active tabPanel is not identified.

Is this a bug or a feature? I know that some elements like DT do not work, but they give a warning, and tabPanel is a standard shiny widget, htmlwidget based.

```
library(shiny)

ui <- fluidPage(
  titlePanel("No shinytest reaction on switching panels"),
  sidebarLayout(
    sidebarPanel(
      tabsetPanel(
        tabPanel(
          title = "First",
          sliderInput("bins", "bins:", min = 1, max = 50, value = 30)
          # ,id = "first" ### There should be an id 
        ), # end First tabPanel
        tabPanel(
          title = "Second",
          checkboxInput("dowhat", "Do Something", value = FALSE)
          # ,id = "second" ### There should be an id
        ), # end second tabPanel
      id = "tabSet"
    ) # end tabsetPanel
  ), # end sidebarPanel
  mainPanel(plotOutput("distPlot"))
  )
)
  
  server <- function(input, output) {
    output$distPlot <- renderPlot({
      x    <- faithful[, 2]
      bins <- seq(min(x), max(x), length.out = input$bins + 1)
      hist(x,
           breaks = bins,
           col = 'darkgray',
           border = 'white')
    })
  }
  
  # Run the application
  shinyApp(ui = ui, server = server)
  ```

**Comment by wch** [comment]
If I record a test with your app, it does record which tab is selected, and the results reflect the selected tab. Here's my test script:

```R
app <- ShinyDriver$new("../")
app$snapshotInit("mytest")
app$snapshot()

app$setInputs(tabSet = "Second")
app$snapshot()
app$setInputs(tabSet = "First")
app$snapshot()
app$setInputs(tabSet = "Second")
app$snapshot()
```

Does it behave differently for you?

Also, I found that there was a typo in the documentation at https://rstudio.github.io/shinytest/articles/in-depth.html#tabs. It says the `tabPanel()` must have an ID, but that's incorrect. It's the `tabsetPanel()` that must have one.

**Comment by dmenne** [comment]
Sorry, my fault. While I had seen from the code that the tabSetPanel must have an ID, I had not checked the generated code after I had added the id in the tabSetPanel.

Thanks.
