### ISSUE TITLE
Docker: localhost didn’t send any data.

### ISSUE THREAD

**Issue by Tazovsky** [rstudio/shinytest#214]
My setup is Docker container running with Rstudio Server on `localhost:3838` from where I'm trying to run `recordTest` but I get error:

> localhost didn’t send any data.

![image](https://user-images.githubusercontent.com/29068994/44629576-b3df4880-a951-11e8-9cd2-07bf942b1980.png)

There are no logs, so it is hard to debug. Any ideas?

**Comment by mtoto** [comment]
What's your Docker container look like?

**Comment by Tazovsky** [comment]
@mtoto I'll prepare MWE. Just give me a bit more time ;)

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
