### ISSUE TITLE
Improve ShinyDriver documentation

### ISSUE THREAD

**Issue by yonicd** [rstudio/shinytest#216]
I have an R6 based [package](https://github.com/yonicd/carbonate) that I created a way to mimic regular R documentation structures. 

here is the rendered version in a [pkgdown site](https://yonicd.github.io/carbonate/reference/carbon.html) for the documentation. 

I think it would be helpful to try and coerce this package's R6 object to a similar layout to make the public methods more accessible and easier to navigate for end users. 

I also got the error below and it took me a good while to figure out what i needed to change. 

```r
setInputs(app$setInputs(begin = "click")): Server did not update any output values within 3 seconds. If this is expected, use `wait_=FALSE, values_=FALSE`, or increase the value of timeout_.
```

**Comment by hadley** [comment]
We could now use roxygen2's built-in support for R6.
