### ISSUE TITLE
negative wait values for expected long waits

### ISSUE THREAD

**Issue by yonicd** [rstudio/shinytest#217]
adding an option for [negative waits](http://toolsqa.com/selenium-webdriver/wait-commands/) would help with variable long timeouts (like in loading large data into the app) in the [js callbacks](https://github.com/rstudio/shinytest/blob/dfc163ca29070bfc6aefb35a6e18d97517c4676b/inst/js/shiny-tracer.js#L171).

Currently the user needs to play with the timeout until it works.

**Comment by hadley** [comment]
I think #327 is probably going to provide a general solution to this. Otherwise, you can easily set an arbitrarily long time out with (e.g.) 1e6.
