### ISSUE TITLE
shiny menuSubItem and body part

### ISSUE THREAD

**Issue by sankarachari** [rstudio/shinytest#218]
I want to display information under menuSubItem under shinydashboard. The structure of submenu for UI in dashboard is as below:
![image](https://user-images.githubusercontent.com/19174901/45279960-481fe280-b4f0-11e8-99d1-8369476483b5.png)

In the above image you can see there are layers menu to reach out till menuSubItem "D", which is shown in green color.

**Below is the code:**
library(shinydashboard)
ui <- dashboardPage(skin = "red",
                    dashboardHeader(title = "sample Dashboard"),
                    dashboardSidebar(sidebarMenu(id = "sidebarmenu", skin = "red"),
                                                 menuItem("A", tabName = "A", 
                                                          menuItem("B", tabName = "B",
                                                                   menuItem("C", tabName = "C", 
                                                                            menuSubItem("D", tabName = "D"))),
                                                                   menuItem("C1", tabName = "C1",
                                                                            menuSubItem("G1", tabName = "G1"))), 
                                                          menuItem("B1", tabName = "B1",
                                                                   menuItem("H", tabName = "H",
                                                                            menuSubItem("I", tabName = "I"))),
                                                  menuItem("A1", tabName = "A1", 
                                                          menuItem("J1", tabName = "J1",
                                                                   menuSubItem("K", tabName = "K"),
                                                                   )))),
                    
                    dashboardBody(
                      tabItems(
                        # First tab content
                        tabItem(tabName = "D", h1("Operation"),
                                fluidRow(
                                  box(plotOutput("plot1", height = 250)),
                                  
                                  box(title = "Controls",
                                      sliderInput("slider", "Number of observations:", 1, 100, 50))
                                )),
                       
                      )
                    )
)
server <- function(input, output) {
  set.seed(122)
  histdata <- rnorm(500)
  
  output$plot1 <- renderPlot({
    data <- histdata[seq_len(input$slider)]
    hist(data)
  })
}
shinyApp(ui, server)

When I click menu item A, it will display another two menus as B and B1. 
When I click B, it will again display two more menus C and C1. 
When I click C, it will display menuSubItem D.
finally when I click D, it should display some plot or some content in body of the App.

I am not able to write a code correctly to reach each of the menuSubItems of the sidebarmenu.

Can any one help me the structure in which I can write for the menuSubItem D, so that it will display content of submenu in the body ?. And so on for I and K are other menuSubItem which are depicted in green color.

Thank you for your support.

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
