### ISSUE TITLE
Rhandsontable package vs shinytest

### ISSUE THREAD

**Issue by kamilsieklucki** [rstudio/shinytest#219]
Hi, have someone used shinytest with app that contains rhot table? 

I've simple example that doesn't work with shinytest. After start a shinytest::recordTest() on this app and change value in cell in rhot table it freezes. Seems that shinytest doesn't work with rhot table.

library(shiny)
library(rhandsontable)

ui <- basicPage(rHandsontableOutput("testing"))

server <- function(input, output, session) {  
  output$testing <- renderRHandsontable({
    rhandsontable(mtcars)              
  })  
}

shinyApp(ui = ui, server = server)

**Comment by FerandDalatieh** [comment]
As mentioned in https://rstudio.github.io/shinytest/articles/in-depth.html#limitations somtimes we need to use JavaScript code to deal with some htmlwidgets (like rhot).

Here is a simple example. Let's say you want to create a test where you take an initial snapshot of your app and then write the value 42 in the 3-rd row and 7-th column. Then take another snapshot.
A test like this would like like the following:

```
app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

# initial snapshot
app$snapshot()

# parameter to be used
newValue <- 42
cellRow <- 3
cellCol <- 7

# write newValue 42 in cell (3,7) of testing table
script <- paste0(
      "var $table = HTMLWidgets.getInstance(testing).hot;",
      "$table.setDataAtCell(", cellRow - 1, ", ", cellCol - 1, ", ", newValue, ");"
      )
# subtract 1 from cellRow and cellCol because JS starts at 0
app$executeScript(script)

# snapshot after the change
app$snapshot()
```
In this way you can manipulate your rhot table and test it :)

**Comment by martin1007** [comment]
Hello,

I am experiencing issues regarding the testing of R shiny web app with shinytest pacakage. My app has many rhandsontables tables with many columns and rows. Thus, what would be the most efficient way to test this kind of application given that usage of $table.setDataAtCell seems to be tedious process because every cell needs to be inputted separately. Please kindly advise.

Thank you in advance.

Regards,
Martin

**Comment by martin1007** [comment]
Hello @FerandDalatieh and @kamilsieklucki, 

Any advise regarding my question? Thank you. 

Regards,
Martin

**Comment by stla** [comment]
For info, one can also do

```r
script <- paste0(
  "document.getElementById('testing').htmlwidget_data_init_result.hot",
  "  .setDataAtCell(", cellRow - 1, ", ", cellCol - 1, ", '", newValue, "');"
)
```
This is useful when the id (here `testing`) contains a minus sign (e.g. if you use Shiny modules). The way above would not work with a minus sign.
