### ISSUE TITLE
Error starting application with HtmlDependency in shinytest

### ISSUE THREAD

**Issue by colearendt** [rstudio/shinytest#222]
This app runs fine, but does not seem to work within the R6 `ShinyDriver` environment. It seems to me that the custom JavaScript the `shinycookie` package loads up is causing a problem somewhere, but I am unaware of how to dig further. At very least, I think this error message should be improved:
```r
shinytest::recordTest()
#Error in sd_startShiny(self, private, path, seed, loadTimeout, shinyOptions) : 
#  Error starting application:
#Running application in test mode.
#Loading required package: shiny
```

Minimal reprex:
```r
library(shiny)
# devtools::install_github("colearendt/shinycookie")
library(shinycookie)
ui <- fluidPage(initShinyCookie("cookie"))
server <- function(input, output, session) {}
shinyApp(ui = ui, server = server)
```

- Put this in `app.R`
- Set as working directory
- run `shinytest::recordTest()`

The `initShinyCookie` function that is causing trouble. I guess one approach could be to whittle this function down to see what causes the issue:

https://github.com/colearendt/shinycookie/blob/50aa62728a140af6d27a14a95c34fc5f570a9239/R/initShinyCookie.R#L14-L36

<details>
<pre>
Session info ------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.2.916.1)         
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2018-10-10                  

Packages ----------------------------------------------------------------
 package     * version    date       source                              
 assertthat    0.2.0      2017-04-11 CRAN (R 3.4.0)                      
 base        * 3.4.3      2017-12-07 local                               
 base64enc     0.1-3      2015-07-28 CRAN (R 3.4.0)                      
 callr         3.0.0      2018-08-24 RSPM (R 3.4.3)                      
 compiler      3.4.3      2017-12-07 local                               
 crayon        1.3.4      2017-09-16 CRAN (R 3.4.1)                      
 curl          3.2        2018-03-28 RSPM (R 3.4.3)                      
 datasets    * 3.4.3      2017-12-07 local                               
 debugme       1.1.0.9000 2018-02-19 Github (gaborcsardi/debugme@f4a116a)
 devtools      1.13.4     2017-11-09 CRAN (R 3.4.2)                      
 digest        0.6.15     2018-01-28 cran (@0.6.15)                      
 graphics    * 3.4.3      2017-12-07 local                               
 grDevices   * 3.4.3      2017-12-07 local                               
 htmltools     0.3.6      2017-04-28 CRAN (R 3.4.0)                      
 httpuv        1.4.5      2018-07-19 RSPM (R 3.4.3)                      
 httr          1.3.1      2017-08-20 RSPM (R 3.4.3)                      
 jsonlite      1.5        2017-06-01 CRAN (R 3.4.0)                      
 later         0.7.3      2018-06-08 RSPM (R 3.4.3)                      
 magrittr      1.5        2014-11-22 CRAN (R 3.4.0)                      
 memoise       1.1.0      2017-04-21 CRAN (R 3.4.0)                      
 methods     * 3.4.3      2017-12-07 local                               
 mime          0.5        2016-07-07 CRAN (R 3.4.0)                      
 packrat       0.4.9-3    2018-06-01 RSPM (R 3.4.3)                      
 parsedate     1.1.3      2017-03-02 RSPM (R 3.4.2)                      
 pingr         1.1.2      2017-03-02 RSPM (R 3.4.2)                      
 png           0.1-7      2013-12-03 RSPM (R 3.4.2)                      
 processx      3.2.0      2018-08-16 RSPM (R 3.4.3)                      
 promises      1.0.1      2018-04-13 RSPM (R 3.4.3)                      
 ps            1.1.0      2018-08-10 RSPM (R 3.4.3)                      
 R6            2.2.2      2017-06-17 CRAN (R 3.4.0)                      
 Rcpp          0.12.18    2018-07-23 RSPM (R 3.4.3)                      
 rematch       1.0.1      2016-04-21 CRAN (R 3.4.0)                      
 rlang         0.2.1      2018-05-30 RSPM (R 3.4.3)                      
 rsconnect     0.8.8      2018-07-05 Github (rstudio/rsconnect@cd0e0aa)  
 rstudioapi    0.7        2017-09-07 RSPM (R 3.4.3)                      
 shiny       * 1.1.0      2018-05-17 RSPM (R 3.4.3)                      
 shinycookie * 0.0.0.9000 2018-10-10 local                               
 shinytest     1.3.0.9000 2018-10-10 Github (rstudio/shinytest@6d30ebf)  
 showimage     1.0.0      2018-01-24 RSPM (R 3.4.2)                      
 stats       * 3.4.3      2017-12-07 local                               
 testthat      2.0.0      2017-12-13 RSPM (R 3.4.2)                      
 tools         3.4.3      2017-12-07 local                               
 utils       * 3.4.3      2017-12-07 local                               
 webdriver     1.0.5      2018-04-11 RSPM (R 3.4.3)                      
 withr         2.1.2      2018-03-15 RSPM (R 3.4.3)                      
 xtable        1.8-2      2016-02-05 CRAN (R 3.4.0)
</pre> 
</details>

**Comment by mcoirad-gmmb** [comment]
I seem to be also having this problem

My session info is also attached
<details>
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shinytest_1.3.0 RPostgres_1.1.1

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.17     compiler_3.5.1   later_0.7.3      base64enc_0.1-3  tools_3.5.1      testthat_2.0.1  
 [7] digest_0.6.18    bit_1.1-14       jsonlite_1.5     debugme_1.1.0    png_0.1-7        pkgconfig_2.0.1 
[13] rlang_0.2.1      shiny_1.1.0      DBI_1.0.0        rstudioapi_0.7   curl_3.2         yaml_2.1.19     
[19] withr_2.1.2      httr_1.3.1       webdriver_1.0.5  hms_0.4.2        bit64_0.9-7      showimage_1.0.0 
[25] parsedate_1.1.3  R6_2.3.0         processx_3.2.0   rematch_1.0.1    pbdZMQ_0.3-3     pingr_1.1.2     
[31] callr_3.0.0      blob_1.1.1       magrittr_1.5     promises_1.0.1   ps_1.2.0         htmltools_0.3.6 
[37] assertthat_0.2.0 mime_0.5         xtable_1.8-2     httpuv_1.4.5     crayon_1.3.4  
<details>

**Comment by colearendt** [comment]
@mcoirad-gmmb Any chance you can share a bit more information about where / how you are having this problem? What you are doing, example reprex, etc.?

**Comment by hadley** [comment]
Now tracking in #329
