### ISSUE TITLE
Issue when testing apps with large amount of data?

### ISSUE THREAD

**Issue by JunlueZhao** [rstudio/shinytest#226]
I have a dashboard app that displays a large table of data. It also converts data into excel format and has a download button to download the output Excel workbook.

1. It is incredibly slow.
2. I make no changes to the program, but each time I run testApp, it is always modified.
------Each time I choose to examine the changes RStudio crashes.
3. When I try to download the Excel output while recording the test, i get this error:
------Running mytest.R Error in curl::curl_fetch_memory(url, handle = handle) : <url> malformed

**Comment by hadley** [comment]
That probably implies you want to take a different approach to testing — see https://mastering-shiny.org/scaling-testing.html for some ideas.
