### ISSUE TITLE
Shiny modals can't be dismissed from shinytest recordings

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shinytest#227]
From @thercast, if your Shiny app shows a modal, dismissing that modal is neither recorded nor possible to programatically initiate (AFAIK).

**Comment by thercast** [comment]
Here is a minimal app that has the three most common popups/notifications I use in my apps (modals via `shiny::modalDialog`, sweet alerts via Dean Attali's [`shinyalert`](https://github.com/daattali/shinyalert) package, and notifications via `shiny::showNotification`):

```r
library(shiny)
library(shinyalert)

ui <- fluidPage(
  useShinyalert(),
  fluidRow(
    # button for typical shiny modal
    actionButton("modal", "Launch Modal"),
    br(),
    # button for shinyalert
    actionButton("alert", "Launch shinyalert"),
    br(),
    # button for shiny notification
    actionButton("note", "Launch notification")
  )
  
)

server <- function(input, output, session) {
  # launch modal
  observeEvent(input$modal, {
    showModal(
      modalDialog(
        title = "Somewhat important message",
        "This is a somewhat important message.",
        easyClose = FALSE
      )
    )
  })
  
  # launch shinyalert
  observeEvent(input$alert, {
    shinyalert(
      title = "Somewhat important message",
      text = "This is a somewhat important message.",
      type = "success",
      closeOnEsc = FALSE,
      closeOnClickOutside = FALSE
    )
  })
  
  # launch notification
  observeEvent(input$note, {
    showNotification("Somewhat important message", duration = NULL, closeButton = TRUE, type = "message")
  })
}

shinyApp(ui = ui, server = server)
```

I intentionally made each of them not "easy" to close (i.e. the user has to click a close element depending on the type of popup).  Here is the script that was produced via `shinytest::recordTest` when clicking each of these buttons and their associated pop-up elements:

```r
app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(modal = "click")
app$setInputs(alert = "click")
# Input 'shinyalert' was set, but doesn't have an input binding.
app$setInputs(note = "click")
app$snapshot()
```

I have somewhat hackish workarounds that involve enabling an easy-close functionality and injecting a key press of say the escape key (happy to provide that if curious).  The other solution is in the case of modal dialogs and shiny alerts, I add a formal action button that has an input element tied to it, so I can click that element programmatically in the test script.

**Comment by LukasK13** [comment]
@rpodcast Thanks for the example, I am facing the same problem. Can you provide your workaround using the escape key?

**Comment by LukasK13** [comment]
If found a solution using the webdriver backend of shinytest. This solution causes the execution of a JavaScipt command (`$('.modal').modal('hide');`) in the headless webbrowser PhantomJS. This JavaScript command hides all shown modal dialogs.
```
app$.__enclos_env__$private$web$executeScript("$('.modal').modal('hide');")
```
@jcheng5  I think this I a valid solution. Should this be implemented as function within the shinytest driver?

**Comment by hadley** [comment]
Alternatively, do the modal buttons have a standard id or other css selector? Then they could be "clicked" using the method proposed in #325

**Comment by LukasK13** [comment]
By default they don‘t have a standard id but have the attribute `data-toggle="modal"` Which can also be selected as `button[data-toggle="modal"]`.

**Comment by hadley** [comment]
Ok, in that case I'm going to close this issue — in the future you'll be able to do `app$findElement("button[data-toggle="modal"]")$click()`.
