### ISSUE TITLE
Set suspendWhenHidden FALSE for all outputs

### ISSUE THREAD

**Issue by akaever** [rstudio/shinytest#237]
Is there a way to set `outputOptions(output, "id", suspendWhenHidden = FALSE)` for all outputs after or when calling `ShinyDriver$new`? For some rendered outputs (e.g. when using `renderPlot`), corresponding code does not seem to be executed/tested in the headless mode. (Don't want to modify this within the server function)

**Comment by hadley** [comment]
I think this is mostly likely because you need to wait for the output to update — see #327 for a proposed fix and work around that you can use currently.
