### ISSUE TITLE
airDatePickerInput testing

### ISSUE THREAD

**Issue by majvdvel** [rstudio/shinytest#252]
Hello, I am currently trying to develop a testing framework for an application which uses some elements of the [shinyWidgets](https://rdrr.io/cran/shinyWidgets/) package.
In this application, the [airDatepicker](https://rdrr.io/cran/shinyWidgets/man/airDatepicker.html) widget is used to select a date and time.

After going through `recordTest()`, I noticed (by using the `takeScreenshot()` function) that the time and date of the widget do not get updated, which results in a failing test. I added a minimal working example below of the application and resulting test code.

app.R:
```
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
   airDatepickerInput(inputId = 'time',
                      label = 'Pick a datetime:',
                      timepicker = TRUE)
)

server <- function(input, output) {}

shinyApp(ui = ui, server = server)
```

mytest.R:
```
app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(time = 1553073900000, wait_ = FALSE, values_ = FALSE)
app$snapshot()
```

**Comment by hadley** [comment]
For now, you'll need to use `app$executeScript()` to manually trigger changes to the input control.

**Comment by DavidPatShuiFong** [comment]
It is possible to use `app$setInputs()` by manually converting the time to JSON.

The clue is in https://github.com/dreamRs/shinyWidgets/blob/master/R/input-airDatepicker.R

For example...

```r
app$setInputs(
  Grocery_List_add_PurchaseDate = as.character(
    jsonlite::toJSON(
      1000 * as.numeric(as.POSIXct(as.Date("2018-05-05"), tz = "UTC")),
      auto_unbox = FALSE)
  )
)
```

(as I used in https://github.com/DavidPatShuiFong/DTedit/blob/develop/tests/datetimeInput/tests/test.R)
