### ISSUE TITLE
Get shinytest::expect_pass() working with devtools::test()

### ISSUE THREAD

**Issue by cpsievert** [rstudio/shinytest#253]
Currently it uses the installed versions of packages no matter what.

**Comment by hadley** [comment]
Do you have a current need for this? Otherwise, I think the plan is to begin to move away from `expect_pass()` in new code.

**Comment by cpsievert** [comment]
Sort of, but it's more of a nice to have than a need. Are you hoping `expect_pass()` will be deprecated in favor of a new testthat function?

**Comment by hadley** [comment]
It wouldn’t be deprecated (since people are already use it) we’d just recommend new tests use finer grained assertions.
