### ISSUE TITLE
''Unable to find input binding for element with id ..."

### ISSUE THREAD

**Issue by annijavarkale** [rstudio/shinytest#255]
I'm getting error `Unable to find input binding for element with id input2` while testing this small example app:
**ui.R**
```
library(shiny)
shinyUI(fluidPage(
    navbarPage("",
               tabPanel("Tab",
                        uiOutput("ui_input1"),
                        tableOutput("pivot1")
               )
               , tabPanel("New tab",
                          uiOutput("ui_input2"),
                          tableOutput("pivot2")
               ))
))
```
**server.R**
```
library(shiny)
shinyServer(function(input, output, session) {
    
    output$ui_input1 <- renderUI({
        numericInput("input1", label = "Nr:", value = 3)
    })
    
    output$ui_input2 <- renderUI({
        numericInput("input2", label = "Nr:", value = 3)
    })
    
    output$pivot1 <- renderTable({
        data.frame(x = rep(x = "X", times = input$input1))
    })
    output$pivot2 <- renderTable({
        data.frame(x = rep(x = "X", times = input$input2))
    })
    
})
```
using **mytest.R**
```
app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(input2 = 4)
app$snapshot()
```
I already tried to put `Sys.sleep(n)`, but it doesn't make any difference. Can someone help me with this? Am I missing something?

**Comment by cpsievert** [comment]
I think you want `uiOutput("input1")` instead of `uiOutput("ui_input1")`?

**Comment by cpsievert** [comment]
For the similar reasons as those discussed [here](https://rstudio.github.io/shinydashboard/behavior.html#testing-with-shinytest), you need to the `id` of `navbarPage()`

Seems like we should add something about this in the [FAQ of shinytest](https://rstudio.github.io/shinytest/articles/faq.html)...

**Comment by wch** [comment]
Also see: https://rstudio.github.io/shinytest/articles/in-depth.html#tabs
