### ISSUE TITLE
expectUpdate and Shiny progress

### ISSUE THREAD

**Issue by rfaelens** [rstudio/shinytest#258]
In issue #82, a bug is described where CSS animations and transitions result in non-repeatable tests.

This was solved by introducing a `Sys.sleep()` condition:
https://github.com/rstudio/shinytest/commit/29f3a23bcf97a102f805a369df1621e0aef26aaa

The same problem appears when using Shiny Progress indicators, modal dialogs and really anything where animations are used in Shiny. The better way to fix this, is to disable all CSS animations entirely.
See https://marcgg.com/blog/2015/01/05/css-animations-failing-capybara-specs/ for a nice description.

This can be done with a simple code:
```{r}
app <- ShinyDriver$new("..", loadTimeout = 30000, seed=1234)
CSS <- "<style>
  * {
    transition-property: none !important;
    -o-transition-property: none !important;
    -moz-transition-property: none !important;
    -ms-transition-property: none !important;
    -webkit-transition-property: none !important;

    transform: none !important;
    -o-transform: none !important;
    -moz-transform: none !important;
    -ms-transform: none !important;
    -webkit-transform: none !important;

    animation: none !important;
    -o-animation: none !important;
    -moz-animation: none !important;
    -ms-animation: none !important;
    -webkit-animation: none !important;
  }
</style>"
CSSJSString <- paste0('"', gsub("\\n", replacement = "\\\\n\" + \n\"", CSS), '"')
js <- paste0('document.getElementsByTagName("head")[0].insertAdjacentHTML("beforeend", ',CSSJSString,');')
with(app$.__enclos_env__, { private$web$executeScript(js) } )
```

Please note that conditionalPanels will also be disabled by this, so this behaviour could be off by default?

**Comment by hadley** [comment]
I think this is something you have to handle on an app-by-app basis; it's not necessarily something that makes sense for shinytest.
