### ISSUE TITLE
Use phantomjs to record image snapshot

### ISSUE THREAD

**Issue by yannrichet** [rstudio/shinytest#266]
[Not sure this has not been posted before...]
I have still (of course) some differences using linux for both recording and comparison of images (btw which may be slighlty contradictory to https://rstudio.github.io/shinytest/articles/ci.html#run_tests-r ...).
I wonder if it should not be possible to use phantomjs (just) to record screenshots (forking current webpage state ?) ?

Anyway, thx for this nice tool !

Y.

**Comment by alandipert** [comment]
Hello, it sounds like this is what you might be looking for: https://github.com/wch/webshot

Closing because this doesn't sound like a problem with shinytest, but please don't hesitate to comment further or create a new issue if I misunderstand.
