### ISSUE TITLE
recordTest results in "'ShinyDriver' not found" error with R earlier than 3.6.0

### ISSUE THREAD

**Issue by ronblum** [rstudio/shinytest#267]
When `shinytest::recordTest` is run on Ubuntu with standalone R, versions older than 3.6.0, the following error occurs:

```
> shinytest::recordTest("~/testy")

Listening on http://127.0.0.1:6084
Warning: Error in eval: object 'ShinyDriver' not found
  61: eval
  60: eval
  59: match.arg
  48: app$getDebugLog
  47: <observer> [/home/rstudio/R/x86_64-pc-linux-gnu-library/3.4/shinytest/recorder/app.R#399]
   4: shiny::runApp
   1: shinytest::recordTest
```

This does not appear to be an issue on SUSE, at least openSUSE 42.3. I believe it's an issue on Red Hat; I'd have to retest. This is using `shinytest` 1.3.2 and `shiny` 1.3.1.

**Comment by ronblum** [comment]
Issue https://github.com/rstudio/rstudio/issues/4555 provides some history, if interested.

**Comment by hadley** [comment]
shinytest now has tests across multiple R versions, and this doesn't appear to come up, so I think it must've been fixed in the interim.
