### ISSUE TITLE
Stop recording event after shiny app closes

### ISSUE THREAD

**Issue by bedantaguru** [rstudio/shinytest#271]
Thanks a lot for this wonderful package. 

Refer to earlier discussion https://github.com/rstudio/rstudio/issues/4054

I tried to record an app after it's closed that's why the error 
`Error in curl::curl_fetch_memory(url, handle = handle): Failed to connect to 127.0.0.1 port <some port>: Connection refused`
comes.

The recorder should stop or show some warning after the shiny app gets closed. 

Here is a screenshot during record
[image](https://github.com/bedantaguru/tidycells_nightly/blob/master/00_nightly_only/shiny_test/exapp/fail_as_clicked_on_done.png )

Here is a reproducible example

The code fails exactly at [this line](https://github.com/bedantaguru/tidycells_nightly/blob/9184c53f9cdf93489b56f68b1cb42890cf851c18/00_nightly_only/shiny_test/exapp/tests/fails_after_close.R#L17).

Also since the example is from GitHub, this is also linked: https://github.com/rstudio/shinytest/issues/270

``` r


# internet is required for this

td <- tempfile("test_dir_")

require(git2r)
#> Loading required package: git2r

clone("https://github.com/bedantaguru/tidycells_nightly", local_path = td, progress = FALSE)
#> Local:    master C:/Users/igayen/AppData/Local/Temp/RtmpmQcftj/test_dir_a281521a1c
#> Remote:   master @ origin (https://github.com/bedantaguru/tidycells_nightly)
#> Head:     [9184c53] 2019-07-31: shinytest github pull push test

setwd(td)

require(shinytest)
#> Loading required package: shinytest
#> Warning: package 'shinytest' was built under R version 3.6.1
#  you need below package (shiny modules are built on this package)
# https://github.com/r-rudra/tidycells 
# devtools::install_github("r-rudra/tidycells")
require(tidycells)
#> Loading required package: tidycells

unlink("00_nightly_only/shiny_test/exapp", recursive = TRUE, force = TRUE)

#  this is exactly same file folder before GitHub push 
#  ref : https://github.com/rstudio/shinytest/issues/270

unzip("00_nightly_only/shiny_test/exapp.zip", exdir = "00_nightly_only/shiny_test")

testApp("00_nightly_only/shiny_test/exapp")
#> Running
#> crop.R fails_after_close.R
#> Error in curl::curl_fetch_memory(url, handle = handle): Failed to connect to 127.0.0.1 port 7681: Connection refused

# cleanup
unlink(td, recursive = TRUE)
```

<sup>Created on 2019-07-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Thanks for filing this bug report! Unfortunately because it's so hard to reproduce or we think it's unlikely to affect many people, we don't have the development resources to fix at this time. It's our policy to close such issues to help stay focussed on the biggest problems, but the issue is still indexed by google, so if other people hit it, they'll be able to find it, and we can consider reopen it if it turns out to be a common problem. Thanks for reporting and I'm sorry we couldn't help more 😞.
