### ISSUE TITLE
RAM Usage Tracking 

### ISSUE THREAD

**Issue by michaelhogersosis** [rstudio/shinytest#274]
Hi there,

For Shiny applications with large number of users it is important to know that the RAM memory usage per session is stable and below a certain threshold. Does shinytest currently track memory usage while testing? If so, how can this information be accessed? 

Alternatively `pryr::mem_used()` could be used to track memory usage over time while testing, nonetheless it might make sense to have RAM tracking enabled when `ShinyDriver$new()` is called given the tendency of Shiny apps to use quite a bit of memory. 

Best regards,

Michael

**Comment by hadley** [comment]
This is out of scope for shinytest; you can use [profvis](https://rstudio.github.io/profvis/) to see memory allocation and possibly consider [shinyloadtest](https://rstudio.github.io/shinyloadtest/) for exploring the performance under load.
