### ISSUE TITLE
Application not generating any output and any export

### ISSUE THREAD

**Issue by tomasj12** [rstudio/shinytest#277]
Hi, 

i am testing quite big application with shinytest, and after i record or run test, in my output json, there is no output, and there is no export.

I have lot of renderPlotly in my app, but when i wrap this function into snapshotPreprocessOutput it does not work. Also in my renderPlotly logic i put export values like this:

``
g <- ggplot(...) ;
p <- ggplotly(g.)
exportTestValues(plot_attrs = p$x$data[[1]]$x)
``
and it does not work.

also when i try app$snapshot(items = list(export = "plot_attrs")) it return me nothing. 

When i record test, and hold ctrl/control and i click on the specific plot/verbatimtextouput or just text, which my shiny render, there is still no output:

``
{
  "output": {

  }
}

``

Can somebody help me ?

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
