### ISSUE TITLE
Using shinytest with modules: object `ShinyDriver` not found

### ISSUE THREAD

**Issue by twollnik** [rstudio/shinytest#283]
## Introduction
I am developing an app that uses modules and am wondering whether it is possible to use shinytest for that app. You can find the source code for the app [here](https://github.com/EarthSystemDiagnostics/cpt-picarr/). The app.R file is [here](https://github.com/EarthSystemDiagnostics/cpt-picarr/blob/master/R/app.R).

I would greatly appreciate you help on this. Thanks in advance!
Tom

## Error

Upon trying to record a test with `shinytest` I got the following error:
```R
Warning: Error in eval: object 'ShinyDriver' not found
  61: eval
  60: eval
  59: match.arg
  48: app$getDebugLog
  47: <observer> [/home/tom/R/x86_64-pc-linux-gnu-library/3.4/shinytest/recorder/app.R#399]
   4: shiny::runApp
   1: shinytest::recordTest
```

## Own research

Looking at the [docs](https://rstudio.github.io/shinytest/reference/ShinyDriver.html) for `ShinyDriver` I found the following piece of information:
> Currently it [ShinyDriver] supports apps that are defined in a single app.R file, or in a server.R and ui.R pair.

It is unclear whether or not this applies to our app. We use modules and helper files, however we also have a file `app.R` that brings all the application logic together.

Looking further I found [this issue](https://github.com/rstudio/shinytest/issues/3) where someone is encountering issues when trying to use shinytest with modules.

I also found [this blog post](https://www.r-bloggers.com/shiny-modules/) that makes it seem like shinytest and modules can be used together. In the blog post they use a different directory structure (app.R in inst/app/; modules in R/). Maybe using the different directory structure can solve my issue.

## Conclusion
It is unclear if we can use `shinytest` for UI testing. Changing the directory structure may help.  Do you have any knowledge about this issue or further ideas?

**Comment by hadley** [comment]
For testing modules, we now recommend using the new `testServer()` — see https://mastering-shiny.org/scaling-testing.html#testing-reactivity for some details.
