### ISSUE TITLE
Restoring values, when test or app is broken

### ISSUE THREAD

**Issue by tomasj12** [rstudio/shinytest#288]
Hi, in my shiny app i have Data tab, where i should load my data. User can specify some options before loading. For example , i have csv file, with semicolon separated file, and the options before loading are:

Data type: Nominal,Ordinal,Binary
Separator: Semicolon, Comma, Tab
Quote: None, Single Quote, Double Quote
Header: TRUE,FALSE
Keep column names: TRUE, FALSE
Keep missing values: TRUE,FALSE.

For example, i want to load example.csv, which is semicolon separated data file, with Nominal data, with no Quote, and i want keep Header, not column names, and also i do not want keep missing values. And then I click on upload button, and data are correctly loaded. 

Also my test should like this:

```r
sep <- ','
data_type <- 'nominal'
itemnames <- FALSE
header <- TRUE
missval <- FALSE
quote <- ''

app <- ShinyDriver$new("../", loadTimeout = 1e+09)

app$setInputs(sep = sep,
                       data_type = data_type,
                       header = header,
                       itemnam = itemnames,
                       missval = missval,
                       quote = quote,
                       wait_ = FALSE, values_ = FALSE,
                       timeout_ = 1e16)

app$uploadFile(data = path_to_example.csv, wait_ = FALSE, values_ = FALSE,
                     timeout_ = 10000000000000000)

app$setInputs(uploadButton = 'click', wait_ = FALSE, values_ = FALSE,
				  timeout_ = 1e10)
```

After this, i successfuly export everything I need for my testing. But we everybody know, that there exist users who made a mistakes, and try what app can do. For example,  user during loading example.csv choose this options:

Data Type : Ordinal
Separator: ';'
Header: TRUE
Keep columnnames : TRUE
Keep missing values: TRUE
Quote: Double Quote

Those options are not suitable for this type of data, and if user click on upload button, app is broken. If i set those values into my test:

```r
sep <- ';'
data_type <- 'ordinal'
itemnames <- TRUE
header <- TRUE
missval <- TRUE
quote <- '" "'


app$setInputs(sep = sep,
                       data_type = data_type,
                       header = header,
                       itemnam = itemnames,
                       missval = missval,
                       quote = quote,
                       wait_ = FALSE, values_ = FALSE,
                       timeout_ = 1e16)

app$uploadFile(data = path_to_example.csv, wait_ = FALSE, values_ = FALSE,
                     timeout_ = 10000000000000000)

app$setInputs(uploadButton = 'click', wait_ = FALSE, values_ = FALSE,
				  timeout_ = 1e10)
```

if i try:

```r
Error in sd_getAllValues(self, private, input, output, export) : 
  Unable to fetch all values from server. Is target app running with options(shiny.testmode=TRUE?)
```

Yes, this is except result, because my app is not ready for this kind of action , and i know, that something is bad. But if i set correct values, again, and make first process, i am still getting error above. Is there any function, or trick, how can i restore values ? Or i need again, before during set of options do this:

```r
app <- ShinyDriver$new("../", loadTimeout = 1e+09)
```

Thanks for your help,

Tomas

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
