### ISSUE TITLE
setInputs not working with editable DT

### ISSUE THREAD

**Issue by cmaguire485** [rstudio/shinytest#289]
Have already asked this elsewhere:
https://github.com/rstudio/DT/issues/716
https://stackoverflow.com/questions/58097212/testing-editable-dt-using-shinytest

Editable DT's work by changing an input e.g. if your table is `output$table1` then your changes will go to `input$table1_cell_edit` as a data frame with columns row, col and value. There seem to be 2 issues here:

1. When recording the test, this input is generated as a vector.
2. Running the test, either as it is generated or by changing the input to what it should be, crashes the app.

Error message:
`Error in sd_getAllValues(self, private, input, output, export) : Unable to fetch all values from server. Is target app running with options(shiny.testmode=TRUE?)`

### Example code:

App:
```
library(shiny)
library(DT)

ui <- fluidPage(
  DTOutput("table"), 
  textOutput("mean")
)

server <- function(input, output) {
  tableUpdate <- reactiveVal(0)
  
  table <- data.frame(A = 1:5, B = 6:10, C = 11:15)
  
  output$table <- renderDT({table},
    options = list(paging = FALSE, dom = 't'),
    selection = 'none',
    server = FALSE,
    editable = list(target = 'row')
  )
  
  observeEvent(input$table_cell_edit, {
    table <<- editData(table, input$table_cell_edit)
    tableUpdate(tableUpdate() + 1)
  })
  
  output$mean <- renderText({
    tableUpdate()
    paste(mean(table$A), mean(table$B), mean(table$C))
  })
}

shinyApp(ui, server)
```

Test: 

```
library(shinytest)

app <- ShinyDriver$new(".")
app$setInputs(table_cell_clicked = list(row = 2, col = 2, value = 7), allowInputNoBinding_ = TRUE)
app$setInputs(table_cell_edit = data.frame(row = 2, col = 0:3, value = "1"), 
              allowInputNoBinding_ = TRUE, priority_ = "event", wait_ = FALSE, values_ = FALSE)
app$takeScreenshot()
app$stop()
rm(app)
```

**Comment by hadley** [comment]
Since you've filed multiple other issues, I'm closing this one.
