### ISSUE TITLE
Suggestion: waitforWidget for complex dynamicUI

### ISSUE THREAD

**Issue by ahmohamed** [rstudio/shinytest#290]
Thanks for making out life easier testing shiny apps.
I have a fairly complex shiny app that uses multiple layers of dynamic UI. I found that using `Sys.sleep` makes testing too slow, since sometimes I don't know precisely how long the UI will take to render.

Similar on `app$waitFor` function, I wrote a rudimentary function that checks when an input widget becomes available:

```r
waitforWidget <- function(app, inputname, interval=1, timeout=60) {
  waited <- 0
  while (!inputname %in% app$listWidgets()$input) {
    Sys.sleep(interval)
    waited <- waited + interval
    if (waited > timeout) {
      stop('App failed to load', inputname, ' in ', timeout, ' seconds')
    }
  }
  message('loaded ', inputname)
}
```

Cheers.

**Comment by hadley** [comment]
See #327 which has a suggestion which you can use in the interim.
