### ISSUE TITLE
Should use ragg for image rendering

### ISSUE THREAD

**Issue by wch** [rstudio/shinytest#291]
ragg provides consistent image output across platforms, so we should consider using it for shinytest. It won't make full-page screenshots consistent because other parts of the web page will use system font rendering, but it should make image hashes consistent across platforms.

**Comment by jcheng5** [comment]
You might also consider using it for Shiny itself... if it works as advertised, I can't think of any downsides

**Comment by wch** [comment]
Agreed. We'll have to be careful to make sure it's stable before we make it the default though.

Note that the fonts aren't necessarily consistent across platforms, so we'll have to figure out how to make that work before it provides any advantages for shinytest.
https://github.com/r-lib/ragg/issues/28

**Comment by hadley** [comment]
(FWIW If you need consistent cross-platform fonts you can use https://cran.r-project.org/web/packages/fontquiver/index.html)

**Comment by hadley** [comment]
Is this really in scope for ShinyTest. Isn't it really the responsibility of the underlying app?

**Comment by hadley** [comment]
I'm pretty sure this is out of scope for shinytest, but please feel free to re-open if you think I'm wrong.
