### ISSUE TITLE
RStudio IDE "Run Tests" with failed expectation generates IDE error

### ISSUE THREAD

**Issue by trestletech** [rstudio/shinytest#295]
In the RStudio IDE:

 - Start with a Shiny app that has no `tests/` dir
 - Record a shinytest via `shinytests::recordTest()`
 - It will bring up the test script at the end. Go into the expected directory and change some value so that the expectations are now wrong (or change the app source)
 - click "Run Tests" in the script that was opened.

<img width="978" alt="Screen Shot 2019-11-04 at 3 05 04 PM" src="https://user-images.githubusercontent.com/1593639/68159637-14044e00-ff4a-11e9-8e1b-cd99cad7df3d.png">

Observe this error.

I think [this](https://github.com/rstudio/rstudio/blob/7626365859391743fd5f947f45ae654360eff31a/src/cpp/session/modules/build/SessionBuildErrors.cpp#L341) is where the IDE is going wrong. Appending `tests/` to the app path and looking in there. As noted in #293, the IDE is already pointing to the wrong appdir path; now appending another invalid path to that one.

From the IDE diagnostics, we're getting that butchered path which didn't go up far enough (i.e. the appdir is `___/tests/`) and now we're assuming that the terminal dir is inevitably called `tests` which gets appended. Thus we're looking for `app/tests/tests/mytest.R` which, of course, doesn't exist.

<img width="460" alt="Screen Shot 2019-11-04 at 3 31 18 PM" src="https://user-images.githubusercontent.com/1593639/68159850-7cebc600-ff4a-11e9-9ae6-656496840d13.png">

**Comment by trestletech** [comment]
Jonathan pointed out that we could add a check into the shinytest package that checks the version of the IDE and presents a warning if it thinks there are going to be issues.

**Comment by hadley** [comment]
Given the overall development resources available to shinytest and the fact that this will naturally resolve itself as people upgrade the ide, I think it's best just to close this issue.
