### ISSUE TITLE
recordTest not works

### ISSUE THREAD

**Issue by jhk0530** [rstudio/shinytest#302]
Hi, 

I'm trying to follow up `shinytest` with documents

<details><summary>Here is my directory information</summary>

```
~/helloworld
  - app.R
  - DESCRIPTION
  - readme.md
  - .Rhistory
  - /tests ( it built automatically )
     - shinytest.R 
     - shinytests/ (EMPTY DIRECTORY)
```

</details>

<details><summary>Below is code for  `app.R` I used, which worked properly on my PC.</summary>

```R
# app.R
library(shiny) # 1.4.0.9001 ver
library(shinytest) # 1.3.1.9001 ver

ui = fluidPage(
  textOutput('out'),
  actionButton('Hi','Btn'),
  numericInput('x','X', NULL),
  textOutput('txt')
)

server = function(input, output, server){
  observeEvent(input$Hi,{
    output$out = renderText("Hello World")
  })
  
  myReactive = reactive({
    input$x * 2
  })  
  
  output$txt = renderText({
    myReactive()
  }) 
}

shinyApp(ui,server)
```

</details>

when I tried `recordTest()` in `application directory(~/helloworld)` 

this error message displayed in console. and also same error when I tried `recordTest(getwd())` or `recordTest('~/helloworld'/)`

![image](https://user-images.githubusercontent.com/6457691/73243503-0ed23a80-41eb-11ea-9275-5ea89812a489.png)

Here is the **line 334** which generated Error. and i think it has broken (at least for my PC). 
I thought maybe encoding caused problem but it didn't worked with `UTF-8` option.

![image](https://user-images.githubusercontent.com/6457691/73243663-7daf9380-41eb-11ea-8e21-11941d707143.png)

so How can I try this `recordTest` function? 

or can I make pull request with fixed that broken character (btw, what is it?)

Regards.

**Comment by wch** [comment]
The symbol is ⌘, which is the "command" button on a Mac. How did you install your version of shinytest? I suspect that when you installed it, something strange happened with the encoding of the file.

**Comment by jhk0530** [comment]
Thanks, It worked at least, but It has still problem. 

the hovering message showed me `&#8984` instead `⌘`


![image](https://user-images.githubusercontent.com/6457691/73292712-df9ce700-4245-11ea-8349-9c17eb407ccf.png)

After exit, it this warning message.

![image](https://user-images.githubusercontent.com/6457691/73293004-69e54b00-4246-11ea-8ea7-5d6179cdfae6.png)

**Comment by wch** [comment]
Can you try installing the latest version of the branch? I made one more change.

I'm not sure what the `readChar` warning is coming from.  Do you see these problems with the CRAN versions of shiny and shinytest?

**Comment by jhk0530** [comment]
![image](https://user-images.githubusercontent.com/6457691/73320661-6d4af780-4283-11ea-8238-9a824b57c337.png)

Now it works well.
However `readChar` warning is still exist.

I can't answer CRAN version of shiny and shinytest shows these too, because CRAN version of shinytest didn't work with parse problem.

**Comment by wch** [comment]
Can you provide the output from `sessioninfo::session_info()`?

**Comment by jhk0530** [comment]
- Session info ------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.2 (2019-12-12)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  Korean_Korea.949            
 ctype    Korean_Korea.949            
 tz       Asia/Seoul                  
 date     2020-02-11                  

- Packages ------------------------------------------------------------------------------------------
 package     * version    date       lib source                            
 assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.1)                    
 base64enc     0.1-3      2015-07-28 [1] CRAN (R 3.6.0)                    
 callr         3.4.1      2020-01-24 [1] CRAN (R 3.6.2)                    
 cli           2.0.1      2020-01-08 [1] CRAN (R 3.6.2)                    
 crayon        1.3.4      2017-09-16 [1] CRAN (R 3.6.1)                    
 curl          4.3        2019-12-02 [1] CRAN (R 3.6.1)                    
 debugme       1.1.0      2017-10-22 [1] CRAN (R 3.6.2)                    
 digest        0.6.23     2019-11-23 [1] CRAN (R 3.6.1)                    
 fansi         0.4.1      2020-01-08 [1] CRAN (R 3.6.2)                    
 fastmap       1.0.1      2019-10-08 [1] CRAN (R 3.6.1)                    
 glue          1.3.1      2019-03-12 [1] CRAN (R 3.6.1)                    
 htmltools     0.4.0.9002 2020-01-28 [1] Github (rstudio/htmltools@e07546c)
 httpuv        1.5.2      2019-09-11 [1] CRAN (R 3.6.1)                    
 httr          1.4.1      2019-08-05 [1] CRAN (R 3.6.1)                    
 jsonlite      1.6.1      2020-02-02 [1] CRAN (R 3.6.2)                    
 later         1.0.0      2019-10-04 [1] CRAN (R 3.6.1)                    
 magrittr      1.5        2014-11-22 [1] CRAN (R 3.6.2)                    
 mime          0.9        2020-02-04 [1] CRAN (R 3.6.2)                    
 parsedate     1.2.0      2019-05-08 [1] CRAN (R 3.6.2)                    
 pingr         2.0.0      2019-10-21 [1] CRAN (R 3.6.2)                    
 png           0.1-7      2013-12-03 [1] CRAN (R 3.6.0)                    
 processx      3.4.2      2020-02-09 [1] CRAN (R 3.6.2)                    
 promises      1.1.0      2019-10-04 [1] CRAN (R 3.6.1)                    
 ps            1.3.0      2018-12-21 [1] CRAN (R 3.6.1)                    
 R6            2.4.1      2019-11-12 [1] CRAN (R 3.6.1)                    
 Rcpp          1.0.3      2019-11-08 [1] CRAN (R 3.6.1)                    
 rematch       1.0.1      2016-04-21 [1] CRAN (R 3.6.2)                    
 rlang         0.4.4      2020-01-28 [1] CRAN (R 3.6.2)                    
 rsconnect     0.8.16     2019-12-13 [1] CRAN (R 3.6.2)                    
 rstudioapi    0.11       2020-02-07 [1] CRAN (R 3.6.2)                    
 sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.1)                    
 shiny       * 1.4.0      2019-10-10 [1] CRAN (R 3.6.2)                    
 shinytest   * 1.3.1      2019-05-06 [1] CRAN (R 3.6.2)                    
 showimage     1.0.0      2018-01-24 [1] CRAN (R 3.6.2)                    
 sourcetools   0.1.7      2018-04-25 [1] CRAN (R 3.6.1)                    
 testthat      2.3.1      2019-12-01 [1] CRAN (R 3.6.2)                    
 webdriver     1.0.5      2018-04-11 [1] CRAN (R 3.6.2)                    
 withr         2.1.2      2018-03-15 [1] CRAN (R 3.6.1)                    
 xtable        1.8-4      2019-04-21 [1] CRAN (R 3.6.1)                    

[1] C:/Users/User/Documents/R/win-library/3.6
[2] C:/Program Files/R/R-3.6.2/library
