### ISSUE TITLE
Can shinytest record zoom/pan events?

### ISSUE THREAD

**Issue by julianstanley** [rstudio/shinytest#312]
I would like to write tests that ensure that I haven't broken the client-side interactive options in htmltools widgets (specifically, customized visNetwork and plotly plots).

So, for example, can I test whether I can successfully pan over a plotly plot?

If I use this example shiny app:

```
library(shiny)
library(plotly)

ui <- fluidPage(
  plotlyOutput("myplot")  
)

server <- function(input, output, session) {
  output$myplot <- renderPlotly({
    plot_ly() %>% add_markers(x = 1:5, y = 51:55)
  })
}

shinyApp(ui, server)
```

I would like to test whether the panning functionality still works.

![panning_test](https://user-images.githubusercontent.com/22749289/83275951-e1e46300-a19d-11ea-860a-ab10a46e9759.gif)
^ A video of me trying to test the pan functionality in the example plotly app.

But the snapshot I took was of the original plot, not the panned one:

![actual_snapshot](https://user-images.githubusercontent.com/22749289/83276187-40a9dc80-a19e-11ea-8207-ab322c099c36.png)
^ The 001.png mytest-expected snapshot

I think this is the same sort of question as #119, but I'm not sure, thus posting a new issue.

Assuming that I'm not missing this functionality somewhere and that it's not trivial to implement, do you have any suggestions on how to test this functionality? Is RSelenium a good option?

**Comment by hadley** [comment]
At this time, you'll need to figure out the javascript events that trigger pan and zoom and emit them yourself using `app$executeScript()`.
