### ISSUE TITLE
shinytest finds size difference in json; difference in json but not in snapshots; huge tests loading problems

### ISSUE THREAD

**Issue by adithirgis** [rstudio/shinytest#315]
I want to build tests which will be consistent (all snapshots will be of same size and font) across platforms but since they have diff resolution, CI would be a better option to tackle this.
1. But when I run the test here the json file has this from Mac
![Size1](https://user-images.githubusercontent.com/63432077/85198739-b8d07180-b308-11ea-9bc9-a503071e35b3.JPG)
and this from Windows
![Size_win](https://user-images.githubusercontent.com/63432077/85198742-be2dbc00-b308-11ea-8258-6252b1dc3496.JPG)
The snapshot has a size difference. I have seen this issue here: https://github.com/rstudio/shinytest/issues/300 and a solution here: https://rstudio.github.io/shinytest/articles/ci.html, I still could not get pass it. 
2. Also when the snapshots match correctly, the json does not and nothing is highlighted as seen above the difference is dark red. 
3. The last issue I faced was the loading of difference even after runtest was completed. 
4. Does this mean making smaller test for a single tab would make sense. Since one of the big tests I wrote and want to update it still does not show me the difference when I run compare test.

**Comment by hadley** [comment]
Cross-platform UI testing is exceptionally difficult because of the all the minor differences across platforms, and it's unfortunately something we don't currently have the resources to support. (But it's a problem that we're aware of and will consider better support in the future).
