### ISSUE TITLE
Testing Applications with Auth0 Login

### ISSUE THREAD

**Issue by masato-yoshihara** [rstudio/shinytest#316]
I'm developing a Shiny application that uses the auth0 R package. As of now, when I use the recordTest function, logs say "Error starting application: Running application in test mode.", and then the application times out before it can completely load all of its dependencies. My hunch is that since my app involves going to the auth0 website outside of the Shiny environment, shinytest doesn't know what inputs to place in to login. Is there anyway to test my application in this situation? Thank you!

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
