### ISSUE TITLE
PhantomJS support

### ISSUE THREAD

**Issue by jcubic** [rstudio/shinytest#317]
PhantomJS is abandoned project and it give lot of issue while testing the application, because you almost can't use any new feature of JavaScript like Promises or any new syntax that is kind of annoying if you only need to support modern browser but can't use anything because of shinyTest.

So my question is do you plan on replacing PhantomJS with something that is maintained? There are other options like Puppeteer or headless Chrome or Selenium (it have driver for headless chrome).

**Comment by wch** [comment]
Yes, we plan on replacing it with headless Chrome in the future. We have an R package for headless Chrome that we'll use:
https://github.com/rstudio/chromote

**Comment by busbyk** [comment]
Since this was closed, is there another issue tracking the future change to headless Chrome over PhantomJS?
