### ISSUE TITLE
Create ShinyDriver from ui + server

### ISSUE THREAD

**Issue by hadley** [rstudio/shinytest#328]
So it's a little easier to test in code. The main challenge is figuring out what additional objects in the current session need to be made available in the session that actually runs the shiny app.

**Comment by hadley** [comment]
Could use `globals::findGlobals()` + `globals::packagesOf()`.

**Comment by DavisVaughan** [comment]
Probably would use `globals::globalsOf()` (which calls `globals::findGlobals()`) + `globals::packagesOf()` on the result

Be aware of `globalsOf(recursive = TRUE)`, which may or may not be what you need
