### ISSUE TITLE
Use phantomJS::onLoadFinished() to detect when page is fully rendered ...

### ISSUE THREAD

**Issue by warnes** [rstudio/shinytest#358]
Ideally, onLoadFinished would toggle the value of a status variable accessible that could be queried and waited on.  Then, perhaps, we could have `app$waitForLoadFinished()` and `app$getLoadFinished()` calls.

**Comment by warnes** [comment]
Also see https://github.com/jonnnnyw/php-phantomjs/issues/85

**Comment by hadley** [comment]
Is this a duplicate of #349?

**Comment by warnes** [comment]
@hadley I think it targets a similar issue, but suggests a different approach.

**Comment by hadley** [comment]
In that case I'll close and this issue will be linked in the discussion.
