### ISSUE TITLE
Make sure dynamic UI is handled properly

### ISSUE THREAD

**Issue by gaborcsardi** [rstudio/shinytest#40]
Maybe we don't need any extra API for it, but nevertheless there should be an easy way to test apps with dynamic UI.

**Comment by gaborcsardi** [comment]
Closed by mistake.

**Comment by Avatoo** [comment]
Sorry, and this one. Is shinytest working with dynamic UI? Seems the auto-generated script is quite subject to change.

**Comment by hadley** [comment]
Is there any evidence that it currently doesn't work?

**Comment by gaborcsardi** [comment]
No?
