### ISSUE TITLE
Running shinyapp$new() gives "Error: Argument 'txt' must be a JSON string, URL or file."

### ISSUE THREAD

**Issue by dbusbridge** [rstudio/shinytest#61]
When on the `testmode-inject-js` branch of `shiny`, running the following code

```
library(shinytest)
app <- shinyapp$new("shiny-examples/050-kmeans-example")
```

yields the warning

```
No encoding supplied: defaulting to UTF-8.
```

which I can probably just ignore as presumably a `httr` function just isn't being given a default somewhere. I also get the error:

```
Error: Argument 'txt' must be a JSON string, URL or file.
```

and I'm not sure where this originates from.

Cheers, Dan

**Comment by wch** [comment]
This seems to be working now.

**Comment by VimalRawat1010** [comment]
Hi,
I am also having same problem with shinytest

> suppressMessages(recordTest("testmeapp/app/"))
Error: Argument 'txt' must be a JSON string, URL or file.

Any suggestions ?

**Comment by wch** [comment]
@VimalRawat1010 Can you open a new issue? And also please supply a reproducible example app.
