### ISSUE TITLE
Running in a build/CI process

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shinytest#64]
I'm guessing shinytest will be heavily used in build scripts and CI. Those workflows usually rely on the test tool to exit with a nonzero status to signal test failure. Perhaps `testApp` should have an option, or make another function, that does the `q(save="no", status=1)` call for you.

And in any case, `testApp` needs to return a programmatic representation of passing/failure (or better yet, of the difference information that resulted from the tests).

**Comment by gaborcsardi** [comment]
The original idea was to run the tests with `testthat`. Then I think you can have a stop reporter that will stop at the first error, if you wish to do that.

**Comment by gaborcsardi** [comment]
It might make sense to create a special `testthat` reporter for `shinytest`, though.

**Comment by hadley** [comment]
Current work around described in https://rstudio.github.io/shinytest/articles/ci.html#run-tests-r
