### ISSUE TITLE
shinytest doesn't work unless attached to search path

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shinytest#65]
Here's what I get if I try to record a test without `library(shinytest)` first:

```
> shinytest::recordTest()
 Error in eval(expr, envir, enclos) : object 'ShinyDriver' not found 
```

**Comment by wch** [comment]
The problem was that `match.arg` requires the default for the argument to be a literal character vector, but it was a vector with a variable as part of it. The `initialize` method's `debug` argument was `debug = c("none", "all", ShinyDriver$debugLogTypes)`:

```R
    initialize = function(path = ".", loadTimeout = 5000,
      checkNames = TRUE,
      debug = c("none", "all", ShinyDriver$debugLogTypes))
      sd_initialize(self, private, path, loadTimeout, checkNames,
                    match.arg(debug, several.ok = TRUE))
```

Changing it to `debug = c("none", "all", "shiny_console", "browser", "shinytest")` fixed it.

**Comment by gaborcsardi** [comment]
The alternative is `shinytest:: ShinyDriver$debugLogTypes`, right? 

This is an annoying bug that does not come up if you use devtools and load all objects from the package....

**Comment by wch** [comment]
@gaborcsardi It looks like you're right -- using an explicit namespace makes it work, so I'll change it to that. I think in general, though, `match.arg` does expect literals, and if you give it something else, the behavior will be strange. I'm not sure what environment it evaluates in. For example:


```R
e <- local({
  A <- R6::R6Class("A",
    public = list(
      initialize = function(x = xdefault) {
        print(force(x))
        print(match.arg(x))
      }
    )
  )
  
  xdefault <- "default"
  environment()
})

e$A$new()
# [1] "default"
# Error in eval(expr, envir, enclos) : object 'xdefault' not found
```

**Comment by gaborcsardi** [comment]
@wch we can also use a five-liner replacement if `match.arg` is too magical.
