### ISSUE TITLE
Very slow (or maybe this is expected?) on Windows

### ISSUE THREAD

**Issue by daattali** [rstudio/shinytest#70]
A simple app like this one takes 5 seconds on Win7 to start up with `recordTest()`:

```
library(shiny)

ui <- fluidPage(
  numericInput("num", "number", 5),
  plotOutput("plot")
)

server <- function(input, output, session) {
  output$plot <- renderPlot({
    plot(seq(input$num))
  })
}

shinyApp(ui = ui, server = server)
```

After changing the value to 6, taking a snapshot, and exiting, this is the script:

```
app <- ShinyDriver$new("..")
app$snapshotInit("mytests")

app$setInputs(num = 6)
app$snapshot()

app$snapshotCompare()
```

And it takes 10 seconds to complete the saving/running of the test. Maybe it takes this long on Mac as well and it's expected, but I feel like if it takes so long every time it will be a huge deterrent to using this tool

**Comment by wch** [comment]
That's in the same ballpark of what I'm seeing on my Mac and in a Windows VM. There's a cost to starting a new R process running the Shiny and PhantomJS. We may be able to improve it at some point by keeping the PhantomJS process around and reusing it.
