### ISSUE TITLE
Can't test download handlers

### ISSUE THREAD

**Issue by daattali** [rstudio/shinytest#72]
It's always very time consuming for me when developing an app to try all sorts of input combinations and making sure the downloaded file is correct. It looks to me like there's no way to test that

**Comment by wch** [comment]
I looked into this a bit, and it seems that PhantomJS doesn't have a way to download files. I think the way to solve this would be to:


* Add a Shiny event like `shiny:fileDownload`
* In shinytest, simulate the download process by grabbing the data directly from the `a` tag's href field.
