### ISSUE TITLE
recordTest() app not working when viewed in the RStudio Viewer Pane (on Windows)

### ISSUE THREAD

**Issue by daattali** [rstudio/shinytest#74]
When shiny apps are set to run in the Viewer Pane by default, only the recorder right column is shown, but not the target app.

Perhaps iframes are not supported

**Comment by wch** [comment]
I'm not able to replicate this with RStudio 1.0.136. What version of RStudio are you using?

**Comment by daattali** [comment]
rstudio v1.1.39

---
R-Shiny Consultant
http://deanattali.com/shiny

**Comment by wch** [comment]
Oh, sorry, I didn't notice that you said the viewer pane, instead of window. That sounds like an RStudio issue, and the viewer pane is generally too small to comfortably fit the recorder with the app anyway.

**Comment by daattali** [comment]
It shouldn't be a size issue, even if I maximize the pane it doesn't show.
Could be RStudio issue

---
R-Shiny Consultant
http://deanattali.com/shiny

**Comment by wch** [comment]
I checked with the RStudio IDE team, and this is apparently an issue with a security setting in RStudio Desktop, which they are planning on fixing in the future.

**Comment by hadley** [comment]
Thanks for filing this bug report! Unfortunately because it's so hard to reproduce or we think it's unlikely to affect many people, we don't have the development resources to fix at this time. It's our policy to close such issues to help stay focussed on the biggest problems, but the issue is still indexed by google, so if other people hit it, they'll be able to find it, and we can consider reopen it if it turns out to be a common problem. Thanks for reporting and I'm sorry we couldn't help more 😞.

**Comment by daattali** [comment]
Thanks Hadley

Since it looks like there will be more issues with a similar fate (the issue persists but will not be resolved due to lack of resources/importance), may I suggest applying a "wontfix" label to all such issues, to help distinguish them from closed+resolved issues

**Comment by hadley** [comment]
Could you please help me understand why you want that? Systematically labelling all closed issues would be a reasonable amount of work (particularly to learn a new workflow for something that's already hard wired into our fingers), we'd have to spend some time figuring out a good set of label names (e.g. it's not really "wontfix" as much as "aren'tfixing"), and already seems obvious from the discussion.

**Comment by daattali** [comment]
I think "wontfix", which is a a default label that github provides, would be good enough - the present vs future tense doesn't change the meaning.

I think it'd help so that when someone arrives at this issue from a search engine, it'll be immediately obvious that  the issue was not resolved. Otherwise if I search for a problem and land on an issue that I see has been closed, my immediate assumption is that it's been dealt with and I'm doing something wrong if it's not working for me. At this point I could either leave the page and spend more time not understanding why I'm still seeing an issue, or I would have to think to look at the discussion to understand the outcome. There are keyboard shortcuts for this if time is the concern.

**Comment by hadley** [comment]
Ok, thanks for the clarification. We don't use the default GitHub labels, and I don't think a small label is likely to help much if you're arriving at an issue with no other context.

**Comment by daattali** [comment]
Systematically applying this retroactively would be a huge hassle, agreed!

I merely suggest that, moving forward, any issue that's closed solely due to lack of resources could have a "wontfix" (or similar, although better to stick with standards IMO) label. I know that for me it really helps to see that information rather than having to read the full discussion.
