### ISSUE TITLE
Idea: some kind of warning when a user is going to overwrite an existing test script

### ISSUE THREAD

**Issue by daattali** [rstudio/shinytest#79]
When you run `recordTest()`, it launches with a default name for the test script. It can be very easy to just run that command twice, hoping to create two separate tests but just going with the default values, which will result in the first test being overwritten. I think it'd be very helpful to either initialize the test script name to a unique name (look at current existing files and add a `-001` etc.) or to tell the user if a file exists with the current name

**Comment by wch** [comment]
This is fixed by edd06ef.
