### ISSUE TITLE
recordTest() sometimes records things that aren't caused by user interaction

### ISSUE THREAD

**Issue by daattali** [rstudio/shinytest#80]
I noticed that when you have a DT table, it fires multiple "input events" that spam the Recorded Events when the table data changes. I don't know if it makes sense to record those events since the user doesn't actually do anything for them to happen. I don't currently have full bug report with code, but if you don't understand this issue I can provide more details

**Comment by wch** [comment]
I have ideas about why this is happening... but a reproducible example would be helpful.

**Comment by daattali** [comment]
I was just playing with recordTest with a few applications I have, and I ran into this problem again (not with DT).

For example, if I update a value using one of the `updateFooInput()` functions, I don't expect that update function to be recorded as a user action - rather, I expect whatever reactive block that was running the code that called this update function to be recorded.

Example:

```
library(shiny)
ui <- fluidPage(
  numericInput("num", "Number", 5),
  actionButton("btn", "Set to 10")
)
server <- function(input, output, session) {
  observeEvent(input$btn, {
    updateNumericInput(session, "num", value = 10)
  })
}
shinyApp(ui, server)
```

If I run `recordTest()` and click the button, it will record two actions:

```
app$setInputs(btn = "click")
app$setInputs(num = 10)
```

Ideally I would want it to only record the first action, because I want to know that my server code is correct and knows to set `num` to 10 when it receives the click message. By "recording" both messages, it loses effectiveness from the test

**Comment by wch** [comment]
Thanks for the report! I just pushed a fix.
