### ISSUE TITLE
Recorder should be aware of output events

### ISSUE THREAD

**Issue by wch** [rstudio/shinytest#92]
When in load test mode, the recorder should be aware of when an input event results in an output change. There are two reasons for this: recording timings between events, and knowing when to set a timeout.

There are two scenarios:
* User sets an input, then sets another input. No output changes between those two steps. In this scenario:
  * It shouldn't wait for values. (The timeout value is irrelevant because it's not waiting.) This makes sense for load testing, because load tests have a `Sys.sleep()` between each input event. However, for correctness testing, there isn't a Sys.sleep() between events -- does it make sense to not wait at all?
  * For load testing, it should record the time between the two input events, and add a `Sys.sleep()` for that amount of time.
* User sets an input, browser receives an output, and then user sets another input. In this scenario:
  * It should wait for values, using a timeout that's (maybe) 3x the actual time it took during recording. This could be used for both load testing and correctness testing.
  * For load testing, it should record the time between the output event and the second input event, and add a `Sys.sleep()` for that amount of time.

**Comment by hadley** [comment]
I think this is going to be rather challenging to impute from app behaviour, and is naturally resolved by hand-rolled tests.
