### ISSUE TITLE
minor but important typo in package vignette

### ISSUE THREAD

**Issue by xhdong-umd** [rstudio/shinytest#93]
The only instruction I can find about using the package is [this](https://rstudio.github.io/shinytest/). But the code for running test is same with recording test:

> To run the test script, do the following:

> library(shinytest)

> # Replace with the correct path
> recordTest("PATH/TO/APP")

It should be `testApp("PATH/TO/APP")`

**Comment by wch** [comment]
I think this has been fixed.
