### ISSUE TITLE
passwordInput was saved in json

### ISSUE THREAD

**Issue by xhdong-umd** [rstudio/shinytest#94]
My app have some user name and password field. The password will be saved in the input json. If we put the test file into git and sync with github, that will make the test password public.

Maybe we should put this kind of input into a special json file and add to .gitignore?

**Comment by wch** [comment]
How would you run an automated test without the password?

**Comment by xhdong-umd** [comment]
Yes I totally understand saving the password is needed. That's why I'm suggesting make it possible to ignore the file in git.

Though on second thought, that still means the test will not run if you were with another machine and just pulled the repo with test files when the password information are ignored.

So there seemed to be no better solution other than not put this kind of test files into public repo.

**Comment by wch** [comment]
You could edit your script to have something like:

```
app$setInput(password = readLines("passwordfile.txt", n=1))
```

Then put your password in `passwordfile.txt` and gitignore that. The git repo of course won't have the password file, but most of the test would be in the repository, which may still be useful.

**Comment by xhdong-umd** [comment]
Yes that will solve the problem. Alternatively I can read password from `~/.Renviron` which would be safer. 

I also realized I can actually ignore the whole `test-expected`, `test-current` directory and only keep the test scripts in repo. When I pulled the repo in another machine, I just need to run the scripts one time to update the expected folder.
