### ISSUE TITLE
cannot take snapshot with app

### ISSUE THREAD

**Issue by xhdong-umd** [rstudio/shinytest#95]
I recorded a test with my app, but all the snapshots taken are the same, just the state of app several seconds after initialization.

There are many warnings in the test script:

```
# Input 'login' was set, but doesn't have an input binding.
# Input 'studies_rows_selected' was set, but doesn't have an input binding.
# Input 'studies_rows_current' was set, but doesn't have an input binding.
# Input 'studies_rows_all' was set, but doesn't have an input binding.
# Input 'studies_state' was set, but doesn't have an input binding.
# Input 'studies_search' was set, but doesn't have an input binding.
# Input 'studies_cell_clicked' was set, but doesn't have an input binding.
# Input 'studies_rows_current' was set, but doesn't have an input binding.
# Input 'studies_rows_all' was set, but doesn't have an input binding.
app$snapshot()
```

If my understanding is correct, the Shiny app in the test recorder is for user input, and there is a invisible target app running in background taking input from recorded user input. So all my user input are recorded, then the invisible target app didn't change state.

This error can be made easy to find if we can include a small thumbnail window showing current status of the invisible target app, maybe just preview each snapshot image. This way the problem can be found much earlier. I made a lot of inputs and records only to find all snapshots are same!

As for the bug itself, my app is [here](https://github.com/ctmm-initiative/ctmm-shiny-prototype). Just choose the radio button in first box `use Buffalo data in ctmm` the app should move to next page and draw some plots. Taking snapshots now will still get the screen in the first page.

**Comment by hadley** [comment]
See the discussion at https://rstudio.github.io/shinytest/articles/in-depth.html#limitations-1 for the details about this message.
