### ISSUE TITLE
Confusion on which repo to install shinytest from

### ISSUE THREAD

**Issue by thercast** [rstudio/shinytest#96]
This might be a minor point, but in the [getting started](https://rstudio.github.io/shinytest/) vignette it states to install `shinytest` with `install_github("MangoTheCat/shinytest")` and not with `install_github("rstudio/shinytest")`.  Obviously I'm aware that Gabor initiated the package, but is his version still considered the most upstream to work with?  I've begun telling colleagues about the package so I want to make sure I give the appropriate repo for the installation.

**Comment by wch** [comment]
Sorry about the confusion. The rstudio/shinytest repo is now the place to install from.  MangoTheCat/shinytest actually was moved to rstudio/shinytest.

Just so you know, there's some work in progress, and it requires the very latest dev version of shiny right now.

**Comment by thercast** [comment]
Thanks Winston!  I figured as much but it's always good to check.
